#pragma once
#include <array>
namespace winchisel::core {
inline constexpr std::array<DebloatCatalogEntry, 72> generated_debloat_catalog{{
    {"windows-app-3d-viewer", "3D Viewer", "windows-app-3d-viewer", DebloatCategory::windows_apps, "3D/Mixed Reality", "Microsoft.Microsoft3DViewer", "Microsoft.Microsoft3DViewer", true, false, "9NBLGGH42THS"},
    {"windows-app-mixed-reality-portal", "Mixed Reality Portal", "windows-app-mixed-reality-portal", DebloatCategory::windows_apps, "3D/Mixed Reality", "Microsoft.MixedReality.Portal", "Microsoft.MixedReality.Portal", true, false, "9NG1H8B3ZC7M"},
    {"windows-app-bing-search", "Bing Search", "windows-app-bing-search", DebloatCategory::windows_apps, "Bing/Search", "Microsoft.BingSearch", "Microsoft.BingSearch", true, false, "9NZBF4GT040C"},
    {"windows-app-microsoft-news", "Microsoft News", "windows-app-microsoft-news", DebloatCategory::windows_apps, "Bing/Search", "Microsoft.BingNews", "Microsoft.BingNews", true, false, "9WZDNCRFHVFW"},
    {"windows-app-msn-weather", "MSN Weather", "windows-app-msn-weather", DebloatCategory::windows_apps, "Bing/Search", "Microsoft.BingWeather", "Microsoft.BingWeather", true, false, "9WZDNCRFJ3Q2"},
    {"windows-app-camera", "Camera", "windows-app-camera", DebloatCategory::windows_apps, "Camera/Media", "Microsoft.WindowsCamera", "Microsoft.WindowsCamera", true, false, "9WZDNCRFJBBG"},
    {"windows-app-clipchamp", "Clipchamp", "windows-app-clipchamp", DebloatCategory::windows_apps, "Camera/Media", "Clipchamp.Clipchamp", "Clipchamp.Clipchamp", true, false, "9P1J8S7CCWWT"},
    {"windows-app-alarms-clock", "Alarms & Clock", "windows-app-alarms-clock", DebloatCategory::windows_apps, "System Utilities", "Microsoft.WindowsAlarms", "Microsoft.WindowsAlarms", true, false, "9WZDNCRFJ3PR"},
    {"windows-app-cortana", "Cortana", "windows-app-cortana", DebloatCategory::windows_apps, "System Utilities", "Microsoft.549981C3F5F10", "Microsoft.549981C3F5F10", false, false, "9NFFX4SZZ23L"},
    {"windows-app-get-help", "Get Help", "windows-app-get-help", DebloatCategory::windows_apps, "System Utilities", "Microsoft.GetHelp", "Microsoft.GetHelp", true, false, "9PKDZBMV1H3T"},
    {"windows-app-calculator", "Calculator", "windows-app-calculator", DebloatCategory::windows_apps, "System Utilities", "Microsoft.WindowsCalculator", "Microsoft.WindowsCalculator", true, false, "9WZDNCRFHVN5"},
    {"windows-app-dev-home", "Dev Home", "windows-app-dev-home", DebloatCategory::windows_apps, "Development", "Microsoft.Windows.DevHome", "Microsoft.Windows.DevHome", true, false, "9N8MHTPHNGVV"},
    {"windows-app-family-safety", "Microsoft Family Safety", "windows-app-family-safety", DebloatCategory::windows_apps, "Communication", "MicrosoftCorporationII.MicrosoftFamily", "MicrosoftCorporationII.MicrosoftFamily", true, false, "9PDJDJS743XF"},
    {"windows-app-mail-calendar", "Mail and Calendar", "windows-app-mail-calendar", DebloatCategory::windows_apps, "Communication", "microsoft.windowscommunicationsapps", "microsoft.windowscommunicationsapps", true, false, "9WZDNCRFHVQM"},
    {"windows-app-skype", "Skype", "windows-app-skype", DebloatCategory::windows_apps, "Communication", "Microsoft.SkypeApp", "Microsoft.SkypeApp", false, false, "9WZDNCRFJ364"},
    {"windows-app-teams", "Microsoft Teams", "windows-app-teams", DebloatCategory::windows_apps, "Communication", "MSTeams", "MSTeams|MicrosoftTeams", true, false, "XP8BT8DW290MPQ"},
    {"windows-app-feedback-hub", "Feedback Hub", "windows-app-feedback-hub", DebloatCategory::windows_apps, "System Tools", "Microsoft.WindowsFeedbackHub", "Microsoft.WindowsFeedbackHub", true, false, "9NBLGGH4R32N"},
    {"windows-app-maps", "Maps", "windows-app-maps", DebloatCategory::windows_apps, "System Tools", "Microsoft.WindowsMaps", "Microsoft.WindowsMaps", true, false, "9WZDNCRDTBVB"},
    {"windows-app-terminal", "Terminal", "windows-app-terminal", DebloatCategory::windows_apps, "System Tools", "Microsoft.WindowsTerminal", "Microsoft.WindowsTerminal", true, false, "9N0DX20HK701"},
    {"windows-app-office-hub", "MS 365 Copilot (Office Hub)", "windows-app-office-hub", DebloatCategory::windows_apps, "Office", "Microsoft.MicrosoftOfficeHub", "Microsoft.MicrosoftOfficeHub", true, false, "9WZDNCRD29V9"},
    {"windows-app-outlook", "Outlook for Windows", "windows-app-outlook", DebloatCategory::windows_apps, "Office", "Microsoft.OutlookForWindows", "Microsoft.OutlookForWindows", true, false, "9NRX63209R7B"},
    {"windows-app-paint-3d", "Paint 3D", "windows-app-paint-3d", DebloatCategory::windows_apps, "Graphics", "Microsoft.MSPaint", "Microsoft.MSPaint", false, false, ""},
    {"windows-app-paint", "Paint", "windows-app-paint", DebloatCategory::windows_apps, "Graphics", "Microsoft.Paint", "Microsoft.Paint", true, false, "9PCFS5B6T72H"},
    {"windows-app-photos", "Photos", "windows-app-photos", DebloatCategory::windows_apps, "Graphics", "Microsoft.Windows.Photos", "Microsoft.Windows.Photos", true, false, "9WZDNCRFJBH4"},
    {"windows-app-snipping-tool", "Snipping Tool", "windows-app-snipping-tool", DebloatCategory::windows_apps, "Graphics", "Microsoft.ScreenSketch", "Microsoft.ScreenSketch", true, false, "9MZ95KL8MR0L"},
    {"windows-app-people", "People", "windows-app-people", DebloatCategory::windows_apps, "Social", "Microsoft.People", "Microsoft.People", true, false, "9NBLGGH10PG8"},
    {"windows-app-power-automate", "Power Automate", "windows-app-power-automate", DebloatCategory::windows_apps, "Automation", "Microsoft.PowerAutomateDesktop", "Microsoft.PowerAutomateDesktop", true, false, "9NFTCH6J7FHV"},
    {"windows-app-quick-assist", "Quick Assist", "windows-app-quick-assist", DebloatCategory::windows_apps, "Support", "MicrosoftCorporationII.QuickAssist", "MicrosoftCorporationII.QuickAssist", true, false, "9P7BP5VNWKX5"},
    {"windows-app-solitaire", "Solitaire Collection", "windows-app-solitaire", DebloatCategory::windows_apps, "Games", "Microsoft.MicrosoftSolitaireCollection", "Microsoft.MicrosoftSolitaireCollection", true, false, "9WZDNCRFHWD2"},
    {"windows-app-xbox", "Xbox", "windows-app-xbox", DebloatCategory::windows_apps, "Games", "Microsoft.GamingApp", "Microsoft.GamingApp|Microsoft.XboxApp", true, false, "9MV0B5HZVK9Z"},
    {"windows-app-xbox-identity-provider", "Xbox Identity Provider", "windows-app-xbox-identity-provider", DebloatCategory::windows_apps, "Games", "Microsoft.XboxIdentityProvider", "Microsoft.XboxIdentityProvider", true, false, "9WZDNCRD1HKW"},
    {"windows-app-xbox-game-bar-plugin", "Xbox Game Bar Plugin", "windows-app-xbox-game-bar-plugin", DebloatCategory::windows_apps, "Games", "Microsoft.XboxGameOverlay", "Microsoft.XboxGameOverlay", true, false, "9NBLGGH537C2"},
    {"windows-app-xbox-live-ingame", "Xbox Live In-Game Experience", "windows-app-xbox-live-ingame", DebloatCategory::windows_apps, "Games", "Microsoft.Xbox.TCUI", "Microsoft.Xbox.TCUI", true, false, "9NKNC0LD5NN6"},
    {"windows-app-xbox-game-bar", "Xbox Game Bar", "windows-app-xbox-game-bar", DebloatCategory::windows_apps, "Games", "Microsoft.XboxGamingOverlay", "Microsoft.XboxGamingOverlay", true, false, "9NZKPSTSNW4P"},
    {"windows-app-store", "Microsoft Store", "windows-app-store", DebloatCategory::windows_apps, "Store", "Microsoft.WindowsStore", "Microsoft.WindowsStore", true, false, "9WZDNCRFJBMP"},
    {"windows-app-media-player", "Media Player", "windows-app-media-player", DebloatCategory::windows_apps, "Media", "Microsoft.ZuneMusic", "Microsoft.ZuneMusic", true, false, "9WZDNCRFJ3PT"},
    {"windows-app-movies-tv", "Movies & TV", "windows-app-movies-tv", DebloatCategory::windows_apps, "Media", "Microsoft.ZuneVideo", "Microsoft.ZuneVideo", true, false, "9WZDNCRFJ3P2"},
    {"windows-app-sound-recorder", "Sound Recorder", "windows-app-sound-recorder", DebloatCategory::windows_apps, "Media", "Microsoft.WindowsSoundRecorder", "Microsoft.WindowsSoundRecorder", true, false, "9WZDNCRFHWKN"},
    {"windows-app-sticky-notes", "Sticky Notes", "windows-app-sticky-notes", DebloatCategory::windows_apps, "Productivity", "Microsoft.MicrosoftStickyNotes", "Microsoft.MicrosoftStickyNotes", true, false, "9NBLGGH4QGHW"},
    {"windows-app-tips", "Tips", "windows-app-tips", DebloatCategory::windows_apps, "Productivity", "Microsoft.Getstarted", "Microsoft.Getstarted", false, false, ""},
    {"windows-app-todo", "To Do: Lists, Tasks & Reminders", "windows-app-todo", DebloatCategory::windows_apps, "Productivity", "Microsoft.Todos", "Microsoft.Todos", true, false, "9NBLGGH5R558"},
    {"windows-app-notepad", "Notepad", "windows-app-notepad", DebloatCategory::windows_apps, "Productivity", "Microsoft.WindowsNotepad", "Microsoft.WindowsNotepad", true, false, "9MSMLRH6LZF3"},
    {"windows-app-phone-link", "Phone Link", "windows-app-phone-link", DebloatCategory::windows_apps, "Phone", "Microsoft.YourPhone", "Microsoft.YourPhone", true, false, "9NMPJ99VJBWV"},
    {"windows-app-copilot", "Copilot", "windows-app-copilot", DebloatCategory::windows_apps, "AI", "Microsoft.Copilot", "Microsoft.Copilot|Microsoft.Windows.Ai.Copilot.Provider|Microsoft.Copilot_8wekyb3d8bbwe", true, false, "9NHT9RB2F4HD"},
    {"windows-app-client-aix", "Windows AI Experience", "windows-app-client-aix", DebloatCategory::windows_apps, "AI", "MicrosoftWindows.Client.AIX", "MicrosoftWindows.Client.AIX", false, false, ""},
    {"windows-app-client-copilot", "Windows Copilot Client", "windows-app-client-copilot", DebloatCategory::windows_apps, "AI", "MicrosoftWindows.Client.CoPilot", "MicrosoftWindows.Client.CoPilot", false, false, ""},
    {"windows-app-edge-game-assist", "Edge Game Assist", "windows-app-edge-game-assist", DebloatCategory::windows_apps, "AI", "Microsoft.Edge.GameAssist", "Microsoft.Edge.GameAssist", false, false, ""},
    {"windows-app-office-actions-server", "Office Actions Server", "windows-app-office-actions-server", DebloatCategory::windows_apps, "AI", "Microsoft.Office.ActionsServer", "Microsoft.Office.ActionsServer", false, false, ""},
    {"windows-app-ai-manager", "AI Manager", "windows-app-ai-manager", DebloatCategory::windows_apps, "AI", "aimgr", "aimgr", false, false, ""},
    {"windows-app-writing-assistant", "Writing Assistant", "windows-app-writing-assistant", DebloatCategory::windows_apps, "AI", "Microsoft.WritingAssistant", "Microsoft.WritingAssistant", false, false, ""},
    {"windows-app-ai-workloads", "AI Workload Packages", "windows-app-ai-workloads", DebloatCategory::windows_apps, "AI", "WindowsWorkload.OnnxRuntimeGenAI", "WindowsWorkload.OnnxRuntimeGenAI|WindowsWorkload.SemanticTextSimilarity|WindowsWorkload.ImageSearch|WindowsWorkload.ContentExtraction|WindowsWorkload.ScreenRegionDetection|WindowsWorkload.TextRecognition|WindowsWorkload.ImageContentModeration|WindowsWorkload.ScreenSemanticsOCR|WindowsWorkload.ImageSuperResolution|WindowsWorkload.ObjectErase|WindowsWorkload.ImageDescriptor|WindowsWorkload.PortraitBlur|WindowsWorkload.TextToSpeech|WindowsWorkload.SpeechToText|WindowsWorkload.ImageSegmentation|WindowsWorkload.CreativeFilter|WindowsWorkload.StudioEffects|WindowsWorkload.SubtitleTranslation|WindowsWorkload.Summarization|WindowsWorkload.RewriteTextSuggestion", false, false, ""},
    {"windows-app-copilot-plus-pc", "Copilot+ PC AI Packages", "windows-app-copilot-plus-pc", DebloatCategory::windows_apps, "AI", "MicrosoftWindows.Voiess", "MicrosoftWindows.Voiess|MicrosoftWindows.Speion|MicrosoftWindows.Livtop|MicrosoftWindows.InpApp|MicrosoftWindows.Filons", false, false, ""},
    {"windows-app-edge", "Microsoft Edge", "windows-app-edge", DebloatCategory::windows_apps, "Browsers", "Microsoft.MicrosoftEdge.Stable", "Microsoft.MicrosoftEdge.Stable", true, false, "XPFFTQ037JWMHS"},
    {"windows-app-onedrive", "OneDrive", "windows-app-onedrive", DebloatCategory::windows_apps, "System", "Microsoft.OneDriveSync", "Microsoft.OneDriveSync", true, false, ""},
    {"windows-app-onenote", "OneNote", "windows-app-onenote", DebloatCategory::windows_apps, "Office", "Microsoft.Office.OneNote", "Microsoft.Office.OneNote", true, false, "XPFFZHVGQWWLHB"},
    {"capability-internet-explorer", "Internet Explorer", "capability-internet-explorer", DebloatCategory::capabilities, "Browser", "Browser.InternetExplorer", "Browser.InternetExplorer", false, false, ""},
    {"capability-powershell-ise", "PowerShell ISE", "capability-powershell-ise", DebloatCategory::capabilities, "Development", "Microsoft.Windows.PowerShell.ISE", "Microsoft.Windows.PowerShell.ISE", true, false, ""},
    {"capability-quick-assist", "Quick Assist", "capability-quick-assist", DebloatCategory::capabilities, "System", "App.Support.QuickAssist", "App.Support.QuickAssist", false, false, ""},
    {"capability-steps-recorder", "Steps Recorder", "capability-steps-recorder", DebloatCategory::capabilities, "Utilities", "App.StepsRecorder", "App.StepsRecorder", true, false, ""},
    {"capability-windows-media-player", "Windows Media Player", "capability-windows-media-player", DebloatCategory::capabilities, "Media", "Media.WindowsMediaPlayer", "Media.WindowsMediaPlayer", true, false, ""},
    {"capability-wordpad", "WordPad", "capability-wordpad", DebloatCategory::capabilities, "Productivity", "Microsoft.Windows.WordPad", "Microsoft.Windows.WordPad", false, false, ""},
    {"capability-notepad", "Notepad (Legacy)", "capability-notepad", DebloatCategory::capabilities, "Productivity", "Microsoft.Windows.Notepad", "Microsoft.Windows.Notepad", false, false, ""},
    {"capability-paint-legacy", "Paint (Legacy)", "capability-paint-legacy", DebloatCategory::capabilities, "Graphics", "Microsoft.Windows.MSPaint", "Microsoft.Windows.MSPaint", false, false, ""},
    {"capability-openssh-client", "OpenSSH Client", "capability-openssh-client", DebloatCategory::capabilities, "Networking", "OpenSSH.Client", "OpenSSH.Client", true, false, ""},
    {"capability-openssh-server", "OpenSSH Server", "capability-openssh-server", DebloatCategory::capabilities, "Networking", "OpenSSH.Server", "OpenSSH.Server", true, false, ""},
    {"feature-wsl", "Subsystem for Linux", "feature-wsl", DebloatCategory::optional_features, "Development", "Microsoft-Windows-Subsystem-Linux", "Microsoft-Windows-Subsystem-Linux", true, true, ""},
    {"feature-hyperv-platform", "Windows Hypervisor Platform", "feature-hyperv-platform", DebloatCategory::optional_features, "Virtualization", "Microsoft-Hyper-V-Hypervisor", "Microsoft-Hyper-V-Hypervisor", true, true, ""},
    {"feature-hyperv", "Hyper-V", "feature-hyperv", DebloatCategory::optional_features, "Virtualization", "Microsoft-Hyper-V-All", "Microsoft-Hyper-V-All", true, true, ""},
    {"feature-hyperv-tools", "Hyper-V Management Tools", "feature-hyperv-tools", DebloatCategory::optional_features, "Virtualization", "Microsoft-Hyper-V-Tools-All", "Microsoft-Hyper-V-Tools-All", true, false, ""},
    {"feature-dotnet35", ".NET Framework 3.5", "feature-dotnet35", DebloatCategory::optional_features, "Development", "NetFx3", "NetFx3", true, true, ""},
    {"feature-windows-sandbox", "Windows Sandbox", "feature-windows-sandbox", DebloatCategory::optional_features, "Security", "Containers-DisposableClientVM", "Containers-DisposableClientVM", true, true, ""},
    {"feature-recall", "Recall", "feature-recall", DebloatCategory::optional_features, "System", "Recall", "Recall", true, false, ""},
}};
}  // namespace winchisel::core
