#pragma once
#include <array>
namespace winchisel::core {
inline constexpr std::array<DownloadCatalogEntry, 176> generated_download_catalog{{
    {"Microsoft EdgeWebView", DownloadCategory::Browsers, "Microsoft.EdgeWebView2Runtime", "https://developer.microsoft.com/en-us/microsoft-edge/webview2/"},
    {"Thorium", DownloadCategory::Browsers, "Alex313031.Thorium", "https://thorium.rocks/"},
    {"Mercury", DownloadCategory::Browsers, "Alex313031.Mercury", "https://thorium.rocks/mercury"},
    {"Mozilla Firefox", DownloadCategory::Browsers, "Mozilla.Firefox", "https://www.mozilla.org/firefox/"},
    {"Google Chrome", DownloadCategory::Browsers, "Google.Chrome|Google.Chrome.EXE", "https://www.google.com/chrome/"},
    {"ungoogled-chromium", DownloadCategory::Browsers, "Eloston.Ungoogled-Chromium", "https://github.com/ungoogled-software/ungoogled-chromium-windows"},
    {"Brave", DownloadCategory::Browsers, "Brave.Brave", "https://brave.com/"},
    {"Opera", DownloadCategory::Browsers, "Opera.Opera", "https://www.opera.com/"},
    {"Opera GX", DownloadCategory::Browsers, "Opera.OperaGX", "https://www.opera.com/gx"},
    {"Arc Browser", DownloadCategory::Browsers, "TheBrowserCompany.Arc", "https://arc.net/"},
    {"Tor Browser", DownloadCategory::Browsers, "TorProject.TorBrowser", "https://www.torproject.org/"},
    {"Vivaldi", DownloadCategory::Browsers, "Vivaldi.Vivaldi", "https://vivaldi.com/"},
    {"Waterfox", DownloadCategory::Browsers, "Waterfox.Waterfox", "https://www.waterfox.net/"},
    {"Zen Browser", DownloadCategory::Browsers, "Zen-Team.Zen-Browser", "https://zen-browser.app/"},
    {"Mullvad Browser", DownloadCategory::Browsers, "MullvadVPN.MullvadBrowser", "https://mullvad.net/en/browser"},
    {"Pale Moon Browser", DownloadCategory::Browsers, "MoonchildProductions.PaleMoon", "https://www.palemoon.org/"},
    {"Maxthon", DownloadCategory::Browsers, "Maxthon.Maxthon", "https://www.maxthon.com/"},
    {"Ablaze Floorp", DownloadCategory::Browsers, "Ablaze.Floorp", "https://floorp.app/"},
    {"DuckDuckGo", DownloadCategory::Browsers, "DuckDuckGo.DesktopBrowser", "https://duckduckgo.com/"},
    {"LibreOffice", DownloadCategory::DocumentViewers, "TheDocumentFoundation.LibreOffice", "https://www.libreoffice.org/"},
    {"ONLYOFFICE Desktop Editors", DownloadCategory::DocumentViewers, "ONLYOFFICE.DesktopEditors", "https://www.onlyoffice.com/"},
    {"PDFgear", DownloadCategory::DocumentViewers, "PDFgear.PDFgear", "https://www.pdfgear.com/"},
    {"Foxit PDF Reader", DownloadCategory::DocumentViewers, "", "https://www.foxit.com/pdf-reader/"},
    {"SumatraPDF", DownloadCategory::DocumentViewers, "SumatraPDF.SumatraPDF", "https://www.sumatrapdfreader.org/"},
    {"OpenOffice", DownloadCategory::DocumentViewers, "Apache.OpenOffice", "https://www.openoffice.org/"},
    {"Adobe Acrobat Reader DC", DownloadCategory::DocumentViewers, "", "https://www.adobe.com/acrobat/pdf-reader.html"},
    {"Evernote", DownloadCategory::DocumentViewers, "Evernote.Evernote", "https://evernote.com/"},
    {"CherryTree", DownloadCategory::DocumentViewers, "Giuspen.Cherrytree", "https://www.giuspen.net/cherrytree/"},
    {"Okular", DownloadCategory::DocumentViewers, "KDE.Okular|KDE.Okular.AppX", "https://okular.kde.org/"},
    {"PDF24 Creator", DownloadCategory::DocumentViewers, "geeksoftwareGmbH.PDF24Creator", "https://www.pdf24.org/"},
    {"Telegram Desktop", DownloadCategory::MessagingEmailCalendar, "Telegram.TelegramDesktop", "https://telegram.org/"},
    {"WhatsApp", DownloadCategory::MessagingEmailCalendar, "", "https://www.whatsapp.com/"},
    {"Zoom Workplace", DownloadCategory::MessagingEmailCalendar, "Zoom.Zoom", "https://zoom.us/"},
    {"Discord", DownloadCategory::MessagingEmailCalendar, "Discord.Discord", "https://discord.com/"},
    {"Pidgin", DownloadCategory::MessagingEmailCalendar, "Pidgin.Pidgin", "https://pidgin.im/"},
    {"Mozilla Thunderbird", DownloadCategory::MessagingEmailCalendar, "Mozilla.Thunderbird", "https://www.thunderbird.net/"},
    {"eM Client", DownloadCategory::MessagingEmailCalendar, "eMClient.eMClient", "https://www.emclient.com/"},
    {"Proton Mail", DownloadCategory::MessagingEmailCalendar, "Proton.ProtonMail", "https://proton.me/mail"},
    {"Trillian", DownloadCategory::MessagingEmailCalendar, "CeruleanStudios.Trillian", "https://www.trillian.im/"},
    {"Google Drive", DownloadCategory::OnlineStorageBackup, "Google.GoogleDrive", "https://www.google.com/drive/"},
    {"Dropbox", DownloadCategory::OnlineStorageBackup, "Dropbox.Dropbox", "https://www.dropbox.com/"},
    {"SugarSync", DownloadCategory::OnlineStorageBackup, "IPVanish.SugarSync", "https://www.sugarsync.com/"},
    {"Nextcloud", DownloadCategory::OnlineStorageBackup, "Nextcloud.NextcloudDesktop", "https://nextcloud.com/"},
    {"Proton Drive", DownloadCategory::OnlineStorageBackup, "Proton.ProtonDrive", "https://proton.me/drive"},
    {"FreeFileSync", DownloadCategory::OnlineStorageBackup, "", "https://freefilesync.org/"},
    {"Hekasoft Backup & Restore", DownloadCategory::OnlineStorageBackup, "Hekasoft.Backup-Restore", "https://hekasoft.com/hekasoft-backup-restore/"},
    {"VLC media player", DownloadCategory::Multimedia, "VideoLAN.VLC", "https://www.videolan.org/vlc/"},
    {"iTunes", DownloadCategory::Multimedia, "Apple.iTunes", "https://www.apple.com/itunes/"},
    {"AIMP", DownloadCategory::Multimedia, "AIMP.AIMP", "https://www.aimp.ru/"},
    {"foobar2000", DownloadCategory::Multimedia, "PeterPawlowski.foobar2000", "https://www.foobar2000.org/"},
    {"MusicBee", DownloadCategory::Multimedia, "", "https://www.getmusicbee.com/"},
    {"Audacity", DownloadCategory::Multimedia, "Audacity.Audacity", "https://www.audacityteam.org/"},
    {"GOM Player", DownloadCategory::Multimedia, "GOMLab.GOMPlayer", "https://www.gomlab.com/"},
    {"Spotify", DownloadCategory::Multimedia, "Spotify.Spotify", "https://www.spotify.com/"},
    {"MediaMonkey", DownloadCategory::Multimedia, "VentisMedia.MediaMonkey.5", "https://www.mediamonkey.com/"},
    {"HandBrake", DownloadCategory::Multimedia, "HandBrake.HandBrake", "https://handbrake.fr/"},
    {"OBS Studio", DownloadCategory::Multimedia, "OBSProject.OBSStudio", "https://obsproject.com/"},
    {"Streamlabs OBS", DownloadCategory::Multimedia, "", "https://streamlabs.com/"},
    {"MPC-BE", DownloadCategory::Multimedia, "MPC-BE.MPC-BE", "https://sourceforge.net/projects/mpcbe/"},
    {"K-Lite Codec Pack (Mega)", DownloadCategory::Multimedia, "CodecGuide.K-LiteCodecPack.Mega", "https://codecguide.com/"},
    {"CapCut", DownloadCategory::Multimedia, "ByteDance.CapCut", "https://www.capcut.com/"},
    {"PotPlayer64", DownloadCategory::Multimedia, "Daum.PotPlayer", "https://potplayer.tv/"},
    {"kdenlive", DownloadCategory::Multimedia, "KDE.Kdenlive", "https://kdenlive.org/"},
    {"MediaInfo", DownloadCategory::Multimedia, "MediaArea.MediaInfo.GUI", "https://mediaarea.net/en/MediaInfo"},
    {"fre:ac - free audio converter", DownloadCategory::Multimedia, "", "https://www.freac.org/"},
    {"SMPlayer", DownloadCategory::Multimedia, "SMPlayer.SMPlayer", "https://www.smplayer.info/"},
    {"Shotcut", DownloadCategory::Multimedia, "Meltytech.Shotcut", "https://www.shotcut.org/"},
    {"LosslessCut", DownloadCategory::Multimedia, "ch.LosslessCut", "https://github.com/mifi/lossless-cut"},
    {"FxSound", DownloadCategory::Multimedia, "FxSound.FxSound", "https://www.fxsound.com/"},
    {"IrfanView64", DownloadCategory::Imaging, "IrfanSkiljan.IrfanView", "https://www.irfanview.com/"},
    {"Krita", DownloadCategory::Imaging, "KDE.Krita", "https://krita.org/"},
    {"Blender", DownloadCategory::Imaging, "BlenderFoundation.Blender", "https://www.blender.org/"},
    {"Paint.NET", DownloadCategory::Imaging, "dotPDN.PaintDotNet", "https://www.getpaint.net/"},
    {"GIMP", DownloadCategory::Imaging, "GIMP.GIMP.3", "https://www.gimp.org/"},
    {"XnViewMP", DownloadCategory::Imaging, "XnSoft.XnViewMP", "https://www.xnview.com/en/xnviewmp/"},
    {"XnView", DownloadCategory::Imaging, "XnSoft.XnView.Classic", "https://www.xnview.com/en/xnview/"},
    {"Inkscape", DownloadCategory::Imaging, "Inkscape.Inkscape", "https://inkscape.org/"},
    {"Greenshot", DownloadCategory::Imaging, "Greenshot.Greenshot", "https://getgreenshot.org/"},
    {"ShareX", DownloadCategory::Imaging, "ShareX.ShareX", "https://getsharex.com/"},
    {"Flameshot", DownloadCategory::Imaging, "Flameshot.Flameshot", "https://flameshot.org/"},
    {"FastStone Image Viewer", DownloadCategory::Imaging, "FastStone.Viewer", "https://www.faststone.org/"},
    {"Nilesoft Shell", DownloadCategory::CustomizationUtilities, "Nilesoft.Shell", "https://nilesoft.org/"},
    {"StartAllBack (Win 11)", DownloadCategory::CustomizationUtilities, "StartIsBack.StartAllBack", "https://www.startallback.com/"},
    {"StartIsBack++ (Win 10)", DownloadCategory::CustomizationUtilities, "StartIsBack.StartIsBack", "https://www.startisback.com/"},
    {"Open-Shell", DownloadCategory::CustomizationUtilities, "Open-Shell.Open-Shell-Menu", "https://open-shell.github.io/Open-Shell-Menu/"},
    {"Windhawk", DownloadCategory::CustomizationUtilities, "RamenSoftware.Windhawk", "https://windhawk.net/"},
    {"Lively Wallpaper", DownloadCategory::CustomizationUtilities, "rocksdanister.LivelyWallpaper", "https://www.rocksdanister.com/lively/"},
    {"Sucrose Wallpaper Engine", DownloadCategory::CustomizationUtilities, "Taiizor.SucroseWallpaperEngine", "https://github.com/Taiizor/Sucrose"},
    {"Rainmeter", DownloadCategory::CustomizationUtilities, "Rainmeter.Rainmeter", "https://www.rainmeter.net/"},
    {"ExplorerPatcher", DownloadCategory::CustomizationUtilities, "valinet.ExplorerPatcher", "https://github.com/valinet/ExplorerPatcher"},
    {"John's Background Switcher", DownloadCategory::CustomizationUtilities, "johnsadventures.JohnsBackgroundSwitcher", "https://johnsad.ventures/software/backgroundswitcher/"},
    {"Microsoft PowerToys", DownloadCategory::CustomizationUtilities, "Microsoft.PowerToys", "https://github.com/microsoft/PowerToys"},
    {"Nexus", DownloadCategory::CustomizationUtilities, "WinStep.Nexus", "https://www.winstep.net/nexus.asp"},
    {"AutoHotkey v2", DownloadCategory::CustomizationUtilities, "AutoHotkey.AutoHotkey", "https://www.autohotkey.com/"},
    {"Steam", DownloadCategory::Gaming, "Valve.Steam", "https://store.steampowered.com/"},
    {"Epic Games Launcher", DownloadCategory::Gaming, "EpicGames.EpicGamesLauncher", "https://www.epicgames.com/"},
    {"7-Zip", DownloadCategory::Compression, "7zip.7zip", "https://www.7-zip.org/"},
    {"WinRAR archiver", DownloadCategory::Compression, "RARLab.WinRAR", "https://www.win-rar.com/"},
    {"PeaZip", DownloadCategory::Compression, "Giorgiotani.Peazip", "https://peazip.github.io/"},
    {"WinDirStat", DownloadCategory::FileDiskManagement, "WinDirStat.WinDirStat", "https://windirstat.net/"},
    {"WizTree", DownloadCategory::FileDiskManagement, "AntibodySoftware.WizTree", "https://www.diskanalyzer.com/"},
    {"TreeSize Free", DownloadCategory::FileDiskManagement, "JAMSoftware.TreeSize.Free", "https://www.jam-software.com/treesize_free"},
    {"Everything", DownloadCategory::FileDiskManagement, "voidtools.Everything", "https://www.voidtools.com/"},
    {"TeraCopy", DownloadCategory::FileDiskManagement, "CodeSector.TeraCopy", "https://www.codesector.com/teracopy"},
    {"File Converter", DownloadCategory::FileDiskManagement, "AdrienAllard.FileConverter", "https://file-converter.io/"},
    {"Crystal Disk Info", DownloadCategory::FileDiskManagement, "WsSolInfor.CrystalDiskInfo", "https://crystalmark.info/en/software/crystaldiskinfo/"},
    {"Bulk Rename Utility", DownloadCategory::FileDiskManagement, "TGRMNSoftware.BulkRenameUtility", "https://www.bulkrenameutility.co.uk/"},
    {"IObit Unlocker", DownloadCategory::FileDiskManagement, "IObit.IObitUnlocker", "https://www.iobit.com/en/iobit-unlocker.php"},
    {"HiBit Uninstaller", DownloadCategory::FileDiskManagement, "HiBitSoftware.HiBitUninstaller", "https://www.hibitsoft.ir/Uninstaller.html"},
    {"SanDisk Dashboard", DownloadCategory::FileDiskManagement, "SanDisk.Dashboard", "https://support-en.sandisk.com/app/products/downloads/softwaredownloads"},
    {"Rufus", DownloadCategory::FileDiskManagement, "Rufus.Rufus", "https://rufus.ie/en/"},
    {"Advanced Renamer", DownloadCategory::FileDiskManagement, "HulubuluSoftware.AdvancedRenamer", "https://www.advancedrenamer.com/"},
    {"RustDesk", DownloadCategory::RemoteAccess, "RustDesk.RustDesk", "https://rustdesk.com/"},
    {"AnyDesk", DownloadCategory::RemoteAccess, "AnyDesk.AnyDesk", "https://anydesk.com/"},
    {"TeamViewer", DownloadCategory::RemoteAccess, "TeamViewer.TeamViewer", "https://www.teamviewer.com/"},
    {"UltraViewer", DownloadCategory::RemoteAccess, "DucFabulous.UltraViewer", "https://www.ultraviewer.net/"},
    {"RealVNC Server", DownloadCategory::RemoteAccess, "RealVNC.VNCServer", "https://www.realvnc.com/"},
    {"RealVNC Viewer", DownloadCategory::RemoteAccess, "RealVNC.VNCViewer", "https://www.realvnc.com/"},
    {"Chrome Remote Desktop", DownloadCategory::RemoteAccess, "Google.ChromeRemoteDesktopHost", "https://remotedesktop.google.com/"},
    {"Parsec", DownloadCategory::RemoteAccess, "Parsec.Parsec", "https://parsec.app/"},
    {"Parsec Virtual Display Driver", DownloadCategory::RemoteAccess, "Parsec.ParsecVDD", "https://parsec.app/"},
    {"Parsec Virtual USB Driver", DownloadCategory::RemoteAccess, "Parsec.ParsecVUD", "https://parsec.app/"},
    {"InputLeap", DownloadCategory::RemoteAccess, "input-leap.input-leap", "https://github.com/input-leap/input-leap"},
    {"ImgBurn", DownloadCategory::OpticalDiscTools, "LIGHTNINGUK.ImgBurn", "https://www.imgburn.com/"},
    {"AnyBurn", DownloadCategory::OpticalDiscTools, "PowerSoftware.AnyBurn", "http://www.anyburn.com/"},
    {"CDBurnerXP", DownloadCategory::OpticalDiscTools, "", "https://cdburnerxp.se/"},
    {"CCleaner", DownloadCategory::OtherUtilities, "Piriform.CCleaner", "https://www.ccleaner.com/"},
    {"Snappy Driver Installer Origin", DownloadCategory::OtherUtilities, "GlennDelahoy.SnappyDriverInstallerOrigin", "https://www.snappy-driver-installer.org/"},
    {"Wise Disk Cleaner", DownloadCategory::OtherUtilities, "WiseCleaner.WiseDiskCleaner", "https://www.wisecleaner.com/wise-disk-cleaner.html"},
    {"Wise Registry Cleaner", DownloadCategory::OtherUtilities, "WiseCleaner.WiseRegistryCleaner", "https://www.wisecleaner.com/wise-registry-cleaner.html"},
    {"UniGetUI", DownloadCategory::OtherUtilities, "MartiCliment.UniGetUI", "https://www.marticliment.com/unigetui/"},
    {"OpenRGB", DownloadCategory::OtherUtilities, "OpenRGB.OpenRGB", "https://openrgb.org/"},
    {"OpenAudible", DownloadCategory::OtherUtilities, "OpenAudible.OpenAudible", "https://openaudible.org/"},
    {"NAPS2", DownloadCategory::OtherUtilities, "Cyanfish.NAPS2", "https://www.naps2.com/"},
    {"IObit Uninstaller", DownloadCategory::OtherUtilities, "IObit.Uninstaller", "https://www.iobit.com/en/advanceduninstaller.php"},
    {"Revo Uninstaller", DownloadCategory::OtherUtilities, "RevoUninstaller.RevoUninstaller", "https://www.revouninstaller.com/products/revo-uninstaller-free/"},
    {"Malwarebytes", DownloadCategory::PrivacySecurity, "Malwarebytes.Malwarebytes", "https://www.malwarebytes.com/"},
    {"Malwarebytes AdwCleaner", DownloadCategory::PrivacySecurity, "Malwarebytes.AdwCleaner", "https://www.malwarebytes.com/adwcleaner"},
    {"Windows Firewall Control", DownloadCategory::PrivacySecurity, "BiniSoft.WindowsFirewallControl", "https://www.binisoft.org/wfc"},
    {"OnionShare", DownloadCategory::PrivacySecurity, "OnionShare.OnionShare", "https://onionshare.org/"},
    {"Sniffnet", DownloadCategory::PrivacySecurity, "", "https://sniffnet.net/"},
    {"TeleGuard", DownloadCategory::PrivacySecurity, "", "https://teleguard.com/en"},
    {"Python 3.13", DownloadCategory::DevelopmentApps, "Python.Python.3.13", "https://www.python.org/"},
    {"Notepad++", DownloadCategory::DevelopmentApps, "Notepad++.Notepad++", "https://notepad-plus-plus.org/"},
    {"WinSCP", DownloadCategory::DevelopmentApps, "WinSCP.WinSCP", "https://winscp.net/"},
    {"PuTTY", DownloadCategory::DevelopmentApps, "PuTTY.PuTTY", "https://www.putty.org/"},
    {"WinMerge", DownloadCategory::DevelopmentApps, "WinMerge.WinMerge", "https://winmerge.org/"},
    {"Eclipse IDE for Java", DownloadCategory::DevelopmentApps, "EclipseFoundation.Eclipse.Java", "https://eclipseide.org/"},
    {"Microsoft Visual Studio Code", DownloadCategory::DevelopmentApps, "Microsoft.VisualStudioCode", "https://code.visualstudio.com/"},
    {"Git", DownloadCategory::DevelopmentApps, "Git.Git", "https://git-scm.com/"},
    {"GitHub Desktop", DownloadCategory::DevelopmentApps, "GitHub.GitHubDesktop", "https://desktop.github.com/"},
    {"Microsoft .NET Runtime 3.1", DownloadCategory::RuntimesDependencies, "Microsoft.DotNet.Runtime.3_1", "https://dotnet.microsoft.com/"},
    {"Microsoft .NET Runtime 5.0", DownloadCategory::RuntimesDependencies, "Microsoft.DotNet.Runtime.5", "https://dotnet.microsoft.com/"},
    {"Microsoft .NET Runtime 6.0", DownloadCategory::RuntimesDependencies, "Microsoft.DotNet.Runtime.6", "https://dotnet.microsoft.com/"},
    {"Microsoft .NET Runtime 7.0", DownloadCategory::RuntimesDependencies, "Microsoft.DotNet.Runtime.7", "https://dotnet.microsoft.com/"},
    {"Microsoft .NET Runtime 8.0", DownloadCategory::RuntimesDependencies, "Microsoft.DotNet.Runtime.8", "https://dotnet.microsoft.com/"},
    {".NET Framework 4.8.1", DownloadCategory::RuntimesDependencies, "Microsoft.DotNet.Framework.DeveloperPack_4", "https://dotnet.microsoft.com/download/dotnet-framework"},
    {"DirectX Runtime", DownloadCategory::RuntimesDependencies, "Microsoft.DirectX", "https://www.microsoft.com/en-us/download/details.aspx?id=35"},
    {"Java Runtime Environment", DownloadCategory::RuntimesDependencies, "Oracle.JavaRuntimeEnvironment", "https://www.oracle.com/java/technologies/downloads/"},
    {"Visual C++ 2005 (x86)", DownloadCategory::RuntimesDependencies, "Microsoft.VCRedist.2005.x86", "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist"},
    {"Visual C++ 2005 (x64)", DownloadCategory::RuntimesDependencies, "Microsoft.VCRedist.2005.x64", "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist"},
    {"Visual C++ 2008 (x86)", DownloadCategory::RuntimesDependencies, "Microsoft.VCRedist.2008.x86", "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist"},
    {"Visual C++ 2008 (x64)", DownloadCategory::RuntimesDependencies, "Microsoft.VCRedist.2008.x64", "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist"},
    {"Visual C++ 2010 (x86)", DownloadCategory::RuntimesDependencies, "Microsoft.VCRedist.2010.x86", "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist"},
    {"Visual C++ 2010 (x64)", DownloadCategory::RuntimesDependencies, "Microsoft.VCRedist.2010.x64", "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist"},
    {"Visual C++ 2012 (x86)", DownloadCategory::RuntimesDependencies, "Microsoft.VCRedist.2012.x86", "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist"},
    {"Visual C++ 2012 (x64)", DownloadCategory::RuntimesDependencies, "Microsoft.VCRedist.2012.x64", "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist"},
    {"Visual C++ 2013 (x86)", DownloadCategory::RuntimesDependencies, "Microsoft.VCRedist.2013.x86", "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist"},
    {"Visual C++ 2013 (x64)", DownloadCategory::RuntimesDependencies, "Microsoft.VCRedist.2013.x64", "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist"},
    {"Visual C++ 2015-2022 (x86)", DownloadCategory::RuntimesDependencies, "Microsoft.VCRedist.2015+.x86", "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist"},
    {"Visual C++ 2015-2022 (x64)", DownloadCategory::RuntimesDependencies, "Microsoft.VCRedist.2015+.x64", "https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist"},
    {"Tabby", DownloadCategory::DevelopmentApps, "Eugeny.Tabby", "https://github.com/Eugeny/tabby"},
    {"Riot Games Launcher", DownloadCategory::Gaming, "", "https://www.riotgames.com/en"},
    {"Helium Browser", DownloadCategory::Browsers, "ImputNet.Helium", "https://github.com/imputnet/helium-windows"},
    {"DataGrip", DownloadCategory::DevelopmentApps, "JetBrains.DataGrip", "https://www.jetbrains.com/datagrip/download/?section=windows"},
    {"Zed", DownloadCategory::DevelopmentApps, "ZedIndustries.Zed", "https://zed.dev/download"},
}};
}  // namespace winchisel::core
