#pragma once
#include <array>
namespace winchisel::core {
inline constexpr std::array<PerformanceCatalogEntry, 114> generated_performance_catalog{{
    {"gaming-game-mode", "Game Mode", "Optimize your PC for gaming by turning things off in the background", 0, 0, ""},
    {"gaming-performance-explorer-mouse-precision", "Enhance Pointer Precision", "Adjust cursor speed based on movement speed (mouse acceleration). Most competitive gamers disable this for consistent aiming in FPS games", 0, 0, ""},
    {"gaming-performance-mouse-hover-time", "Mouse Hover Time", "Controls how long you have to hover over an element before it becomes active (in milliseconds). Lower values cause tooltips, menus and hover effects to appear faster. The default value is 400 ms", 0, 1, "1ms (Instant)|10ms (Very Fast)|50ms (Fast)|100ms (Moderate)|200ms|400ms (Default)"},
    {"gaming-performance-autostart-delay", "Startup Delay for Apps", "Delay the launch of applications for 10 seconds after startup to improve initial system responsiveness. Windows becomes faster to use, but your startup apps take longer to load", 0, 0, ""},
    {"gaming-background-apps", "Let Apps Run in Background", "Use Group Policy to control whether apps can run in the background. Force Deny removes per-app background settings from Windows Settings. Use User in Control if you need apps like Teams, Zoom or WhatsApp", 0, 1, "User in Control (Default)|Force Allow|Force Deny"},
    {"gaming-storage-sense", "Storage Sense", "Automatically free up space by removing temporary files, emptying the trash, and managing downloads", 0, 0, ""},
    {"gaming-performance-explorer-search", "Search Entire File System", "Search your entire file system instead of just indexed locations. This provides more complete results, but is significantly slower than indexed search and increases disk activity", 0, 0, ""},
    {"gaming-performance-search-webview2", "WebView2 in Windows Search", "Allow Windows Search to use WebView2 (Edge) to render search results. Disabling it will remove edge processes created by SearchHost.exe, thereby reducing resource usage. Uses an undocumented Windows Feature Management override (Feature ID 37926450), which may change in future Windows updates", 0, 0, ""},
    {"gaming-performance-wallpaper-compression", "Allow Desktop Wallpaper Compression", "Allow Windows to compress wallpapers to save disk space and improve performance. Only affects images in JPEG format.", 0, 0, ""},
    {"gaming-performance-explorer-menu-show-delay", "Enable Menu Show Delay", "Add a short delay before menus appear (400ms - Windows default) or show them immediately (0ms) to speed up navigation", 0, 0, ""},
    {"gaming-explorer-alt-tab-filter", "Alt+Tab Filter", "Alt+Tab only shows traditional open windows instead of including Microsoft Edge tabs and other Windows suggestions", 0, 0, ""},
    {"gaming-win32-priority", "Adjust processor for best performance of", "Configure how Windows allocates CPU time between foreground applications and background services", 1, 1, "Programs|Background Services"},
    {"gaming-system-responsiveness", "System Responsiveness for Games", "Minimize disruption from background tasks by allocating more CPU time to your active game or multimedia application", 1, 0, ""},
    {"gaming-cpu-priority", "CPU Priority for Gaming", "Give games a higher CPU scheduling priority to dedicate more processor time to your game", 1, 0, ""},
    {"gaming-scheduling-category", "High Scheduling Category for Gaming", "Assign a high priority scheduling category to ensure games receive preferential system resource allocation", 1, 0, ""},
    {"gaming-performance-svchost-split-threshold", "Svchost Split Threshold", "Set the memory threshold that determines when Windows splits services into separate svchost.exe processes. Higher values group more services together, reducing the number of processes. Select the value that corresponds to your system RAM", 1, 1, "Default|4 GB|6 GB|8 GB|12 GB|16 GB|24 GB|32 GB|64 GB|128 GB|Custom"},
    {"gaming-gpu-priority", "GPU Priority for Gaming", "Give games a higher GPU scheduling priority to improve graphics performance and frame rates", 2, 0, ""},
    {"gaming-gpu-scheduling", "Hardware-Accelerated GPU Scheduling", "Let your GPU manage its own memory and scheduling to reduce latency and improve performance", 2, 0, ""},
    {"gaming-directx-flip-model", "Optimizations for windowed games", "Reduce latency and leverage advanced features in compatible games by using the DirectX Flip presentation model", 2, 0, ""},
    {"gaming-directx-vrr-optimizations", "Variable Refresh Rate", "Enable VRR optimizations (G-Sync/FreeSync) for smoother gameplay. Requires a VRR compatible monitor; This setting has no effect if your monitor does not support VRR", 2, 0, ""},
    {"gaming-directx-auto-hdr", "Auto HDR", "Automatically convert SDR content to HDR to improve colors and brightness. Requires an HDR-capable display with HDR enabled; This setting has no effect if your display does not support HDR", 2, 0, ""},
    {"gaming-nvidia-sharpening", "Legacy NVIDIA Sharpening", "Enable the legacy NVIDIA image sharpening filter for improved visual clarity. Only works with older NVIDIA drivers; Newer drivers should use NVIDIA Control Panel sharpening instead", 2, 0, ""},
    {"gaming-fullscreen-optimizations", "Fullscreen Optimizations", "Allow Windows to optimize games running in full screen mode. Disabling it may resolve performance issues or stuttering in some older games that don't work well with borderless fullscreen optimization", 2, 0, ""},
    {"gaming-performance-desktop-composition", "Desktop Composition Effects", "Enable visual effects managed by Desktop Window Manager. Disabling this may provide small performance gains on older hardware, but will affect aero effects", 2, 0, ""},
    {"gaming-auto-color-management", "Automatically manage color for apps", "Allow Windows to automatically manage color profiles for all connected displays that support it", 2, 0, ""},
    {"gaming-disable-mpo", "Multi-Plane Overlay (MPO)", "Compositing multiple display layers in hardware using the GPU. Disabling it can resolve screen flickering, black screens, and stuttering in multi-monitor configurations", 2, 0, ""},
    {"gaming-disable-mpo-min-fps", "MPO Minimum Frame Rate Requirement", "Enable Desktop Window Managers to dynamically switch apps between overlay modes based on frame rate. Disabling it can fix stuttering in browsers and Discord without having to completely disable MPO", 2, 0, ""},
    {"gaming-network-throttling", "Network Throttling", "Controls network packet rate limiting for multimedia applications. It is recommended to leave throttling enabled (default: 10 packets/ms) as it provides better DPC latency for gaming than disabling it completely", 3, 0, ""},
    {"gaming-nagle-algorithm", "Nagle's Algorithm", "Buffers small network packets before sending to reduce overhead. Turn it off to reduce latency during online gaming or leave it on for overall network efficiency", 3, 0, ""},
    {"gaming-dns-server", "DNS Server", "Select a DNS server for all network adapters. Changes apply to each adapter in your system (WiFi and Ethernet). Use 'Automatic' to restore your default ISP/Router DNS", 3, 1, "Automatic (System Default)|Cloudflare (1.1.1.1)|Cloudflare Malware (1.1.1.2)|Cloudflare Family (1.1.1.3)|Google (8.8.8.8)|Quad9 (9.9.9.9)|OpenDNS (208.67.222.222)|Custom (User Defined)"},
    {"gaming-virtualization-based-security", "Virtualization Based Security (VBS)", "Isolates portions of memory to protect the system from vulnerabilities. Disabling it may improve gaming performance but reduces system security", 4, 0, ""},
    {"gaming-memory-integrity", "Memory Integrity (HVCI)", "Prevents the introduction of malicious code into high-security processes. Disabling it may improve gaming performance but reduces system security", 4, 0, ""},
    {"gaming-xbox-game-dvr", "Xbox Game DVR", "Record gameplay clips and take screenshots with the Xbox Game Bar overlay. Disabling this reduces CPU/GPU usage and can improve frame rates", 5, 0, ""},
    {"gaming-game-bar-controller", "Game Bar Controller Access", "Allow your Xbox or compatible controller to open the Game Bar by pressing the Xbox button. Disable this option to prevent accidental activation of the Game Bar while playing", 5, 0, ""},
    {"gaming-game-bar-tips", "Game Bar Tips and Hints", "Displays tips and hints about Game Bar features when the overlay opens. Disabling it will reduce distractions during gameplay", 5, 0, ""},
    {"gaming-performance-background-services", "Optimize Background Services", "Reduce the startup timeout for Windows services from 60 to 30 seconds. This may reduce boot time slightly", 6, 0, ""},
    {"gaming-sysmain-service", "SysMain Service (Superfetch)", "Preload frequently used applications into RAM for faster boot times. Automatic is recommended for hard drives or mixed storage systems; 'Manual' or 'Disabled' is only suitable for pure SSD systems", 6, 1, "Disabled (Recommended for SSD)|Manual|Automatic (Recommended for HDD)"},
    {"gaming-performance-prefetch", "Prefetch Feature", "Preload frequently used applications and boot files into memory to speed up startup. Generally recommended for HDDs and not SSDs", 6, 0, ""},
    {"gaming-windows-search-service", "Windows Search Indexing Service", "Indexes files and folders for faster search results. Disabling it will reduce CPU and disk activity in the background, but will break Outlook search and make Start menu and File Explorer search slow or unreliable", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-print-spooler-service", "Print Spooler Service", "Manages print jobs sent to printers. If you are not using a printer, set it to Manual or Disabled to free up system resources", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-telemetry-service", "Connected User Experiences and Telemetry Service", "Sends usage data and diagnostics to Microsoft. Setting it to Manual or Disabled reduces background network and CPU usage", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-connected-devices-platform-service", "Connected Devices Platform Service", "Enables cross-device experiences like phone linking and nearby sharing. Disabling reduces background activity and logging of device interactions", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-compatibility-assistant-service", "Program Compatibility Assistant Service", "Monitors programs for compatibility issues and suggests fixes. Disabling it will prevent compatibility prompts and save minor system resources", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-error-reporting-service", "Windows Error Reporting Service", "Collects and sends crash data to Microsoft. Disabling it prevents crash reports, reduces network traffic, and improves data protection with minimal impact to the system", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-geolocation-service", "Geolocation Service", "Tracks your physical location for apps and services. Disabling improves privacy and prevents location tracking, but apps cannot use location features", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-retail-demo-service", "Retail Demo Service", "Controls device activity in retail demo mode. For PCs, disabling may be safe as it is for retail display purposes only", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-insider-service", "Windows Insider Service", "Manages Windows Insider Program features and preview builds. Deactivation is safe if you do not participate in the Windows Insider Program", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-phone-service", "Phone Service", "Manages telephony status on the device. You can easily disable the feature if you don't use phone connection features or don't make calls from your PC", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-wallet-service", "Wallet Service", "Provides wallet functionality for payment and NFC scenarios. It is safe to deactivate if you do not use Microsoft Wallet features", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-smart-card-services", "Smart Card Services", "Enables the smart card reader function for security authentication. Deactivation is safe if you do not use physical smart cards or card readers", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-maps-broker-service", "Downloaded Maps Manager", "Provides access to downloaded maps for applications. Set the option to Manual to allow access to the map when needed while preventing unnecessary background activity", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-fax-service", "Fax Service", "Allows you to send and receive faxes. For most users, disabling it is safe because the fax feature is rarely used on modern systems", 6, 1, "Disabled (Recommended)|Manual|Automatic"},
    {"gaming-wmp-network-service", "Windows Media Player Network Sharing Service", "Shares Windows Media Player libraries with other networked players and media devices. You can safely disable the feature if you don't share media over your network", 6, 1, "Disabled (Recommended)|Manual|Automatic"},
    {"gaming-mixed-reality-service", "Windows Mixed Reality OpenXR Service", "Runs OpenXR applications on Windows Mixed Reality devices. It's safe to deactivate if you don't use VR or AR headsets", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-mobile-hotspot-service", "Windows Mobile Hotspot Service", "Provides the ability to share the Internet connection with other devices. Set to Manual to keep functionality available while preventing unnecessary background activity", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-sms-router-service", "Microsoft Windows SMS Router Service", "Forwards SMS messages according to rules. You can safely disable the feature if you don't use SMS features on your PC", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-parental-controls-service", "Parental Controls Service", "Enables parental controls and family safety features. You can safely disable the feature if you don't use parental control features", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-payments-nfc-service", "Payments and NFC/SE Manager", "Manages payments and secure elements of near field communication. It is safe to deactivate if you do not use the NFC payment functions", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-spot-verifier-service", "Spot Verifier Service", "Checks for possible file system corruption. Set the option to Manual to enable checking when needed while reducing background activity", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-remote-access-manager", "Remote Access Connection Manager", "Manages VPN and dial-up connections. Set to Manual to reduce background activity while keeping VPN functionality available when needed.", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-remote-access-auto", "Remote Access Auto Connection Manager", "Automatically connects to remote networks when programs reference remote resources. You can safely disable the feature if you don't use the VPN's auto-connect features", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-remote-desktop-services", "Remote Desktop Services", "Allows users to interactively connect to a remote computer. Set to Manual to reduce background activity while keeping remote desktop available.", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-remote-desktop-configuration", "Remote Desktop Configuration", "Manages Remote Desktop Services and Remote Desktop-related configurations. Set to Manual to reduce background activity while keeping remote desktop available", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-remote-desktop-port-redirector", "Remote Desktop Services UserMode Port Redirector", "Enables local device redirection for remote desktop connections. It's safe to disable if you don't need to share local devices during remote desktop sessions", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-xbox-auth-manager", "Xbox Live Auth Manager", "Provides authentication and authorization services for Xbox Live. It's safe to deactivate if you don't use Xbox Game Pass, Microsoft Store games, or Xbox features", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-xbox-game-save", "Xbox Live Game Save", "Syncs save games to the Xbox Live cloud. Only required for Xbox Game Pass and Microsoft Store games with cloud save capabilities", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-xbox-networking", "Xbox Live Networking Service", "Supports Xbox Live multiplayer networks. Required for Xbox multiplayer games, but not for Steam/Epic/other gaming platforms", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-biometric-service", "Windows Biometric Service", "Enables fingerprint and facial recognition login via Windows Hello. Safe to disable on desktop systems without biometric hardware", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-touch-keyboard-service", "Touch Keyboard and Handwriting Panel Service", "Manages the Windows input experience, including touch keyboard, pen/stylus input, handwriting panel, emoji panel (Win+.), and Xbox controller keyboard. Disabling this will break all virtual/software keyboard input, but is safe on desktop systems without a touchscreen, stylus, or gamepad", 6, 1, "Disabled (Recommended)|Manual|Automatic"},
    {"gaming-sensor-monitoring-service", "Sensor Monitoring Service", "Monitors various sensors such as ambient light and orientation. Safe to disable on desktop systems without sensor hardware", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-sensor-data-service", "Sensor Data Service", "Delivers data from a variety of sensors to applications. Safe to disable on desktop systems without sensor hardware", 6, 1, "Disabled|Manual (Recommended)|Automatic"},
    {"gaming-ai-fabric-service", "Windows AI Fabric Service", "Windows AI Fabric Service (WSAIFabricSvc) manages AI workloads. Disable this option if you do not use Windows AI features", 6, 1, "Disabled (Recommended)|Manual|Automatic"},
    {"CompatibilityAppraiserTask", "Microsoft Compatibility Appraiser Task", "Collects program compatibility telemetry data for Windows upgrades. Works in conjunction with the Connected User Experiences and Telemetry service. Disable to reduce telemetry and background system activity", 7, 0, ""},
    {"ProgramDataUpdaterTask", "Program Data Updater Task", "Updates the program compatibility database with information about installed applications. Disable this option to reduce telemetry collection", 7, 0, ""},
    {"CEIPConsolidatorTask", "Customer Experience Improvement Program Consolidator", "Consolidates and uploads usage data as part of the customer experience improvement program. Works with the Connected User Experiences and Telemetry service. Disable to improve privacy", 7, 0, ""},
    {"UsbCeipTask", "USB CEIP Task", "Collects USB device related telemetry data for customer satisfaction improvement program. Disable to reduce telemetry", 7, 0, ""},
    {"DiskDiagnosticTask", "Disk Diagnostic Data Collector Task", "Collects hard drive diagnostic information and S.M.A.R.T. Data for Microsoft. Disable this option to reduce background disk activity and telemetry", 7, 0, ""},
    {"FeedbackDmClientTask", "Feedback DmClient Task", "Collects feedback and diagnostic data for Microsoft. Disable this option to improve privacy and reduce telemetry", 7, 0, ""},
    {"FeedbackDmClientDownloadTask", "Feedback DmClient Scenario Download Task", "Downloads feedback scenarios and configuration data from Microsoft. Disable to reduce telemetry and network activity", 7, 0, ""},
    {"ErrorReportingQueueTask", "Windows Error Reporting Queue Task", "Queues crash reports and error data to be sent to Microsoft. Works in conjunction with the Windows Error Reporting Service. Disable both to prevent crash data collection", 7, 0, ""},
    {"SqmTask", "Software Quality Metrics Task", "Collects software quality metrics and reliability data for Microsoft telemetry. Disable to improve privacy", 7, 0, ""},
    {"MareBackupTask", "MAR (Malicious Software Removal) Backup Task", "Backs up Microsoft Assisted Recovery data. Disable this option to reduce system activity in the background", 7, 0, ""},
    {"StartupAppTask", "Startup App Task", "Tracks and monitors startup applications for telemetry and diagnostics. Disable to reduce telemetry", 7, 0, ""},
    {"MapsUpdateTask", "Maps Update Task", "Updates offline map data for the Windows Maps app. Disable this option when you are not using the Maps app to save bandwidth and storage space", 7, 0, ""},
    {"AutochkProxyTask", "AutoChk Proxy Task", "Performs hard drive checks and collects diagnostic data. Consider leaving disk health monitoring enabled", 7, 0, ""},
    {"FamilySafetyTask", "Family Safety Monitor Task", "Monitors family security settings and usage. Disable this option if you do not use the family safety features", 7, 0, ""},
    {"PowerEfficiencyTask", "Power Efficiency Diagnostics Task", "Analyzes system power consumption and collects energy efficiency data. Disable this option to reduce telemetry and background analysis", 7, 0, ""},
    {"WindowsAIRecallConfig", "Windows AI Recall Configuration Task", "Scheduled Windows AI tasks, including recall configuration. Disable this option to prevent AI features from running in the background", 7, 0, ""},
    {"WindowsAIRecallPipeline", "Windows AI Recall Pipeline Task", "Windows AI Recall Pipeline Task. Disable this option to prevent the recall pipeline from processing in the background", 7, 0, ""},
    {"OfficeActionsServer", "Office Actions Server Task", "Office AI Actions Server scheduled task. Disable this option to prevent Office AI from running in the background", 7, 0, ""},
    {"visual-effects-mode", "Visual Effects", "Choose how Windows displays visual effects", 8, 1, "Let Windows choose what's best for my computer|Adjust for best appearance|Adjust for best performance|Custom"},
    {"ui-effects", "Animate controls and elements inside windows", "Enables animation effects for controls and UI elements", 8, 0, ""},
    {"window-animation", "Animate windows when minimizing and maximizing", "Displays a smooth animation when windows are minimized or maximized", 8, 0, ""},
    {"taskbar-animations", "Animations in the taskbar", "Controls the taskbar animation effects for opening, closing, and switching windows", 8, 0, ""},
    {"enable-peek", "Enable Peek", "Allows you to view the desktop when you hover over the Show Desktop button", 8, 0, ""},
    {"menu-animation", "Fade or slide menus into view", "Animates menus when displayed using fade or slide effects", 8, 0, ""},
    {"fade-tooltip", "Fade or slide ToolTips into view", "Animates tooltips when displayed using fade or slide effects", 8, 0, ""},
    {"fade-menu-items", "Fade out menu items after clicking", "Hides menu items after selection before closing the menu", 8, 0, ""},
    {"taskbar-thumbnails", "Save taskbar thumbnail previews", "Saves thumbnail previews of taskbar windows for faster viewing", 8, 0, ""},
    {"mouse-shadow", "Show shadows under mouse pointer", "Displays a shadow effect under the mouse pointer", 8, 0, ""},
    {"window-shadows", "Show shadows under windows", "Displays shadow effects under windows", 8, 0, ""},
    {"show-thumbnails", "Show thumbnails instead of icons", "Displays image and document previews instead of generic file icons", 8, 0, ""},
    {"translucent-selection", "Show translucent selection rectangle", "Display a semi-transparent selection box as you drag to select multiple files or items", 8, 0, ""},
    {"drag-full-windows", "Show window contents while dragging", "When you drag, displays the window contents instead of just an outline", 8, 0, ""},
    {"combo-box-animation", "Slide open combo boxes", "Animates combo boxes when opened with a sliding effect", 8, 0, ""},
    {"font-smoothing", "Smooth edges of screen fonts", "Apply anti-aliasing to text for smoother, more readable fonts on the screen", 8, 0, ""},
    {"smooth-scroll-listboxes", "Smooth-scroll list boxes", "Allows smooth scrolling in list boxes instead of jumping", 8, 0, ""},
    {"drop-shadows", "Use drop shadows for icon labels on the desktop", "Add shadow effects behind desktop icon text to improve readability against the background", 8, 0, ""},
    {"gaming-narrator-hotkey", "Narrator Win+Ctrl+Enter Hotkey", "Enable the Win+Ctrl+Enter keyboard shortcut to quickly launch the Windows Narrator screen reader", 9, 0, ""},
    {"accessibility-stickykeys-hotkey", "StickyKeys Hotkey (Shift+5)", "Activate the keyboard shortcut to activate StickyKeys by pressing the Shift key five times", 9, 0, ""},
    {"accessibility-filterkeys-hotkey", "FilterKeys Hotkey (Right Shift 8s)", "Enable the keyboard shortcut to enable FilterKeys by holding down the right Shift key for 8 seconds", 9, 0, ""},
    {"accessibility-togglekeys-hotkey", "ToggleKeys Hotkey (Num Lock 5s)", "To activate ToggleKeys, activate the keyboard shortcut by holding down the Num Lock key for 5 seconds. This will play sounds when the Caps Lock/Num Lock/Scroll key is pressed", 9, 0, ""},
    {"accessibility-mousekeys-hotkey", "MouseKeys Hotkey (Alt+Shift+NumLock)", "Enable the keyboard shortcut to enable MouseKeys, which allows using the numeric keypad to control the mouse pointer", 9, 0, ""},
    {"accessibility-highcontrast-hotkey", "High Contrast Hotkey (Alt+Shift+PrtScn)", "To enable High Contrast mode, activate the keyboard shortcut by pressing Left Alt + Left Shift + Screen Print", 9, 0, ""},
}};
inline constexpr std::array<PerformanceRegistryRule, 68> generated_performance_registry_rules{{
    {"gaming-game-mode", "Software\\Microsoft\\GameBar", "AutoGameModeEnabled", "1|__MISSING__", "0", 0, 0, -1, 0},
    {"gaming-performance-explorer-mouse-precision", "Control Panel\\Mouse", "MouseSpeed", "1", "0", 0, 1, -1, 0},
    {"gaming-performance-autostart-delay", "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Serialize", "StartupDelayInMSec", "10000", "0", 0, 0, -1, 0},
    {"gaming-storage-sense", "SOFTWARE\\Policies\\Microsoft\\Windows\\StorageSense", "AllowStorageSenseGlobal", "1|__MISSING__", "0", 0, 0, -1, 0},
    {"gaming-storage-sense", "SOFTWARE\\Policies\\Microsoft\\Windows\\StorageSense", "AllowStorageSenseGlobal", "1|__MISSING__", "0", 1, 0, -1, 0},
    {"gaming-performance-explorer-search", "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Search\\Preferences", "WholeFileSystem", "1", "0", 0, 0, -1, 0},
    {"gaming-performance-search-webview2", "SYSTEM\\CurrentControlSet\\Control\\FeatureManagement\\Overrides\\8\\1694661260", "EnabledState", "2", "1", 1, 0, -1, 0},
    {"gaming-performance-search-webview2", "SYSTEM\\CurrentControlSet\\Control\\FeatureManagement\\Overrides\\8\\1694661260", "EnabledStateOptions", "__MISSING__", "0", 1, 0, -1, 0},
    {"gaming-performance-search-webview2", "SYSTEM\\CurrentControlSet\\Control\\FeatureManagement\\Overrides\\8\\1694661260", "Variant", "__MISSING__", "0", 1, 0, -1, 0},
    {"gaming-performance-search-webview2", "SYSTEM\\CurrentControlSet\\Control\\FeatureManagement\\Overrides\\8\\1694661260", "VariantPayload", "__MISSING__", "0", 1, 0, -1, 0},
    {"gaming-performance-search-webview2", "SYSTEM\\CurrentControlSet\\Control\\FeatureManagement\\Overrides\\8\\1694661260", "VariantPayloadKind", "__MISSING__", "0", 1, 0, -1, 0},
    {"gaming-performance-wallpaper-compression", "Control Panel\\Desktop", "JPEGImportQuality", "0|__MISSING__", "100", 0, 0, -1, 0},
    {"gaming-performance-explorer-menu-show-delay", "Control Panel\\Desktop", "MenuShowDelay", "400", "0", 0, 1, -1, 0},
    {"gaming-explorer-alt-tab-filter", "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced", "MultiTaskingAltTabFilter", "3", "0", 0, 0, -1, 0},
    {"gaming-system-responsiveness", "Software\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile", "SystemResponsiveness", "10", "20", 1, 0, -1, 0},
    {"gaming-cpu-priority", "Software\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "Priority", "6", "2", 1, 0, -1, 0},
    {"gaming-scheduling-category", "Software\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "Scheduling Category", "High", "Medium", 1, 1, -1, 0},
    {"gaming-gpu-priority", "Software\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games", "GPU Priority", "8", "2", 1, 0, -1, 0},
    {"gaming-gpu-scheduling", "System\\CurrentControlSet\\Control\\GraphicsDrivers", "HwSchMode", "2|__MISSING__", "1", 1, 0, -1, 0},
    {"gaming-directx-flip-model", "Software\\Microsoft\\DirectX\\UserGpuPreferences", "DirectXUserGlobalSettings", "1", "0", 0, 1, -1, 0},
    {"gaming-directx-vrr-optimizations", "Software\\Microsoft\\DirectX\\UserGpuPreferences", "DirectXUserGlobalSettings", "1", "0", 0, 1, -1, 0},
    {"gaming-directx-auto-hdr", "Software\\Microsoft\\DirectX\\UserGpuPreferences", "DirectXUserGlobalSettings", "1", "0", 0, 1, -1, 0},
    {"gaming-nvidia-sharpening", "Software\\NVIDIA Corporation\\Global\\FTS", "EnableGR535", "0", "1", 1, 0, -1, 0},
    {"gaming-fullscreen-optimizations", "System\\GameConfigStore", "GameDVR_FSEBehaviorMode", "0", "2", 0, 0, -1, 0},
    {"gaming-performance-desktop-composition", "Software\\Microsoft\\Windows\\DWM", "CompositionPolicy", "__MISSING__", "0", 0, 0, -1, 0},
    {"gaming-auto-color-management", "SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\MonitorDataStore", "AutoColorManagementEnabled", "1", "0", 1, 0, -1, 0},
    {"gaming-disable-mpo", "SOFTWARE\\Microsoft\\Windows\\Dwm", "OverlayTestMode", "__MISSING__", "5", 1, 0, -1, 0},
    {"gaming-disable-mpo", "SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers", "DisableOverlays", "__MISSING__", "1", 1, 0, -1, 0},
    {"gaming-disable-mpo-min-fps", "SOFTWARE\\Microsoft\\Windows\\Dwm", "OverlayMinFPS", "__MISSING__", "0", 1, 0, -1, 0},
    {"gaming-network-throttling", "Software\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile", "NetworkThrottlingIndex", "10", "-1", 1, 0, -1, 0},
    {"gaming-nagle-algorithm", "SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces", "TcpAckFrequency", "__MISSING__", "1", 1, 0, -1, 0},
    {"gaming-nagle-algorithm", "SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces", "TCPNoDelay", "__MISSING__", "1", 1, 0, -1, 0},
    {"gaming-virtualization-based-security", "SYSTEM\\CurrentControlSet\\Control\\DeviceGuard", "EnableVirtualizationBasedSecurity", "1", "0", 1, 0, -1, 0},
    {"gaming-virtualization-based-security", "SYSTEM\\CurrentControlSet\\Control\\DeviceGuard", "RequirePlatformSecurityFeatures", "1", "0", 1, 0, -1, 0},
    {"gaming-virtualization-based-security", "SYSTEM\\CurrentControlSet\\Control\\DeviceGuard", "Locked", "1", "0", 1, 0, -1, 0},
    {"gaming-memory-integrity", "SYSTEM\\CurrentControlSet\\Control\\DeviceGuard\\Scenarios\\HypervisorEnforcedCodeIntegrity", "Enabled", "1", "0", 1, 0, -1, 0},
    {"gaming-memory-integrity", "SYSTEM\\CurrentControlSet\\Control\\DeviceGuard\\Scenarios\\HypervisorEnforcedCodeIntegrity", "Locked", "1", "0", 1, 0, -1, 0},
    {"gaming-memory-integrity", "SYSTEM\\CurrentControlSet\\Control\\DeviceGuard\\Scenarios\\HypervisorEnforcedCodeIntegrity", "WasEnabledBy", "2", "0", 1, 0, -1, 0},
    {"gaming-xbox-game-dvr", "System\\GameConfigStore", "GameDVR_Enabled", "1", "0", 0, 0, -1, 0},
    {"gaming-xbox-game-dvr", "Software\\Microsoft\\Windows\\CurrentVersion\\GameDVR", "AppCaptureEnabled", "1", "0", 0, 0, -1, 0},
    {"gaming-xbox-game-dvr", "SOFTWARE\\Policies\\Microsoft\\Windows\\GameDVR", "AllowGameDVR", "1", "0", 1, 0, -1, 0},
    {"gaming-game-bar-controller", "Software\\Microsoft\\GameBar", "UseNexusForGameBarEnabled", "__MISSING__", "0", 0, 0, -1, 0},
    {"gaming-game-bar-tips", "Software\\Microsoft\\GameBar", "ShowStartupPanel", "__MISSING__", "0", 0, 0, -1, 0},
    {"gaming-performance-background-services", "SYSTEM\\CurrentControlSet\\Control", "ServicesPipeTimeout", "30000", "60000", 1, 0, -1, 0},
    {"gaming-performance-prefetch", "SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters", "EnablePrefetcher", "3", "0", 1, 0, -1, 0},
    {"ui-effects", "Control Panel\\Desktop", "UserPreferencesMask", "1", "0", 0, 2, 4, 2},
    {"window-animation", "Control Panel\\Desktop\\WindowMetrics", "MinAnimate", "1", "0", 0, 1, -1, 0},
    {"taskbar-animations", "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced", "TaskbarAnimations", "1", "0", 0, 0, -1, 0},
    {"enable-peek", "Software\\Microsoft\\Windows\\DWM", "EnableAeroPeek", "1", "0", 0, 0, -1, 0},
    {"menu-animation", "Control Panel\\Desktop", "UserPreferencesMask", "1", "0", 0, 2, 0, 2},
    {"fade-tooltip", "Control Panel\\Desktop", "UserPreferencesMask", "1", "0", 0, 2, 1, 8},
    {"fade-menu-items", "Control Panel\\Desktop", "UserPreferencesMask", "1", "0", 0, 2, 1, 4},
    {"taskbar-thumbnails", "Software\\Microsoft\\Windows\\DWM", "AlwaysHibernateThumbnails", "1", "0", 0, 0, -1, 0},
    {"mouse-shadow", "Control Panel\\Desktop", "UserPreferencesMask", "1", "0", 0, 2, 1, 32},
    {"window-shadows", "Control Panel\\Desktop", "UserPreferencesMask", "1", "0", 0, 2, 2, 4},
    {"show-thumbnails", "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced", "IconsOnly", "0", "1", 0, 0, -1, 0},
    {"translucent-selection", "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced", "ListviewAlphaSelect", "1", "0", 0, 0, -1, 0},
    {"drag-full-windows", "Control Panel\\Desktop", "DragFullWindows", "1", "0", 0, 1, -1, 0},
    {"combo-box-animation", "Control Panel\\Desktop", "UserPreferencesMask", "1", "0", 0, 2, 0, 4},
    {"font-smoothing", "Control Panel\\Desktop", "FontSmoothing", "2", "0", 0, 1, -1, 0},
    {"smooth-scroll-listboxes", "Control Panel\\Desktop", "UserPreferencesMask", "1", "0", 0, 2, 0, 8},
    {"drop-shadows", "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced", "ListviewShadow", "1", "0", 0, 0, -1, 0},
    {"gaming-narrator-hotkey", "Software\\Microsoft\\Narrator\\NoRoam", "WinEnterLaunchEnabled", "__MISSING__", "0", 0, 0, -1, 0},
    {"accessibility-stickykeys-hotkey", "Control Panel\\Accessibility\\StickyKeys", "Flags", "510", "2", 0, 1, -1, 0},
    {"accessibility-filterkeys-hotkey", "Control Panel\\Accessibility\\Keyboard Response", "Flags", "126", "2", 0, 1, -1, 0},
    {"accessibility-togglekeys-hotkey", "Control Panel\\Accessibility\\ToggleKeys", "Flags", "62", "34", 0, 1, -1, 0},
    {"accessibility-mousekeys-hotkey", "Control Panel\\Accessibility\\MouseKeys", "Flags", "126", "130", 0, 1, -1, 0},
    {"accessibility-highcontrast-hotkey", "Control Panel\\Accessibility\\HighContrast", "Flags", "126", "4194", 0, 1, -1, 0},
}};
inline constexpr std::array<PerformanceProfileRule, 113> generated_performance_profile_rules{{
    {"gaming-game-mode", 1, 1, -1, -1},
    {"gaming-performance-explorer-mouse-precision", 0, 1, -1, -1},
    {"gaming-performance-mouse-hover-time", -1, -1, 0, 5},
    {"gaming-performance-autostart-delay", 0, 0, -1, -1},
    {"gaming-background-apps", -1, -1, 2, 0},
    {"gaming-storage-sense", 0, 1, -1, -1},
    {"gaming-performance-explorer-search", 0, 0, -1, -1},
    {"gaming-performance-search-webview2", 0, 1, -1, -1},
    {"gaming-performance-wallpaper-compression", 0, 1, -1, -1},
    {"gaming-performance-explorer-menu-show-delay", 0, 1, -1, -1},
    {"gaming-explorer-alt-tab-filter", 1, 1, -1, -1},
    {"gaming-win32-priority", -1, -1, 0, 0},
    {"gaming-system-responsiveness", 1, 0, -1, -1},
    {"gaming-cpu-priority", 1, 0, -1, -1},
    {"gaming-scheduling-category", 1, 0, -1, -1},
    {"gaming-performance-svchost-split-threshold", -1, -1, 0, 0},
    {"gaming-gpu-priority", 1, 0, -1, -1},
    {"gaming-gpu-scheduling", 1, 1, -1, -1},
    {"gaming-directx-flip-model", 1, 1, -1, -1},
    {"gaming-directx-vrr-optimizations", 0, 1, -1, -1},
    {"gaming-directx-auto-hdr", 0, 0, -1, -1},
    {"gaming-nvidia-sharpening", 1, 0, -1, -1},
    {"gaming-fullscreen-optimizations", 1, 1, -1, -1},
    {"gaming-performance-desktop-composition", 1, 1, -1, -1},
    {"gaming-auto-color-management", 0, 0, -1, -1},
    {"gaming-disable-mpo", 1, 1, -1, -1},
    {"gaming-disable-mpo-min-fps", 1, 1, -1, -1},
    {"gaming-network-throttling", 1, 1, -1, -1},
    {"gaming-nagle-algorithm", 1, 1, -1, -1},
    {"gaming-dns-server", -1, -1, 0, 0},
    {"gaming-virtualization-based-security", 0, 1, -1, -1},
    {"gaming-memory-integrity", 0, 1, -1, -1},
    {"gaming-xbox-game-dvr", 0, 1, -1, -1},
    {"gaming-game-bar-controller", 0, 1, -1, -1},
    {"gaming-game-bar-tips", 0, 1, -1, -1},
    {"gaming-performance-background-services", 1, 0, -1, -1},
    {"gaming-sysmain-service", -1, -1, 0, 2},
    {"gaming-performance-prefetch", 0, 1, -1, -1},
    {"gaming-windows-search-service", -1, -1, 1, 2},
    {"gaming-print-spooler-service", -1, -1, 1, 2},
    {"gaming-telemetry-service", -1, -1, 1, 2},
    {"gaming-connected-devices-platform-service", -1, -1, 1, 2},
    {"gaming-compatibility-assistant-service", -1, -1, 1, 2},
    {"gaming-error-reporting-service", -1, -1, 1, 1},
    {"gaming-geolocation-service", -1, -1, 1, 1},
    {"gaming-retail-demo-service", -1, -1, 1, 1},
    {"gaming-insider-service", -1, -1, 1, 1},
    {"gaming-phone-service", -1, -1, 1, 1},
    {"gaming-wallet-service", -1, -1, 1, 1},
    {"gaming-smart-card-services", -1, -1, 1, 1},
    {"gaming-maps-broker-service", -1, -1, 1, 2},
    {"gaming-fax-service", -1, -1, 0, 0},
    {"gaming-wmp-network-service", -1, -1, 0, 1},
    {"gaming-mixed-reality-service", -1, -1, 1, 0},
    {"gaming-mobile-hotspot-service", -1, -1, 1, 1},
    {"gaming-sms-router-service", -1, -1, 1, 1},
    {"gaming-parental-controls-service", -1, -1, 1, 1},
    {"gaming-payments-nfc-service", -1, -1, 1, 1},
    {"gaming-spot-verifier-service", -1, -1, 1, 1},
    {"gaming-remote-access-manager", -1, -1, 1, 1},
    {"gaming-remote-access-auto", -1, -1, 1, 1},
    {"gaming-remote-desktop-services", -1, -1, 1, 1},
    {"gaming-remote-desktop-configuration", -1, -1, 1, 1},
    {"gaming-remote-desktop-port-redirector", -1, -1, 1, 1},
    {"gaming-xbox-auth-manager", -1, -1, 1, 1},
    {"gaming-xbox-game-save", -1, -1, 1, 1},
    {"gaming-xbox-networking", -1, -1, 1, 1},
    {"gaming-biometric-service", -1, -1, 1, 1},
    {"gaming-touch-keyboard-service", -1, -1, 0, 1},
    {"gaming-sensor-monitoring-service", -1, -1, 1, 1},
    {"gaming-sensor-data-service", -1, -1, 1, 1},
    {"gaming-ai-fabric-service", -1, -1, 0, 2},
    {"gaming-task-compatibility-appraiser", -1, -1, -1, -1},
    {"gaming-task-program-data-updater", -1, -1, -1, -1},
    {"gaming-task-ceip-consolidator", -1, -1, -1, -1},
    {"gaming-task-usb-ceip", -1, -1, -1, -1},
    {"gaming-task-disk-diagnostic", -1, -1, -1, -1},
    {"gaming-task-feedback-dmclient", -1, -1, -1, -1},
    {"gaming-task-feedback-dmclient-download", -1, -1, -1, -1},
    {"gaming-task-error-reporting-queue", -1, -1, -1, -1},
    {"gaming-task-sqm", -1, -1, -1, -1},
    {"gaming-task-mare-backup", -1, -1, -1, -1},
    {"gaming-task-startup-app", -1, -1, -1, -1},
    {"gaming-task-maps-update", -1, -1, -1, -1},
    {"gaming-task-autochk-proxy", -1, -1, -1, -1},
    {"gaming-task-family-safety", -1, -1, -1, -1},
    {"gaming-task-power-efficiency", -1, -1, -1, -1},
    {"gaming-task-windows-ai", -1, -1, -1, -1},
    {"gaming-task-office-actions-server", -1, -1, -1, -1},
    {"visual-effects-mode", -1, -1, 3, 0},
    {"ui-effects", 0, 1, -1, -1},
    {"window-animation", 0, 1, -1, -1},
    {"taskbar-animations", 0, 1, -1, -1},
    {"enable-peek", 1, 1, -1, -1},
    {"menu-animation", 0, 1, -1, -1},
    {"fade-tooltip", 0, 1, -1, -1},
    {"fade-menu-items", 0, 1, -1, -1},
    {"taskbar-thumbnails", 0, 0, -1, -1},
    {"mouse-shadow", 0, 1, -1, -1},
    {"window-shadows", 0, 1, -1, -1},
    {"show-thumbnails", 1, 1, -1, -1},
    {"translucent-selection", 1, 1, -1, -1},
    {"drag-full-windows", 1, 1, -1, -1},
    {"combo-box-animation", 0, 1, -1, -1},
    {"font-smoothing", 1, 0, -1, -1},
    {"smooth-scroll-listboxes", 0, 1, -1, -1},
    {"drop-shadows", 0, 1, -1, -1},
    {"gaming-narrator-hotkey", 0, 1, -1, -1},
    {"accessibility-stickykeys-hotkey", 0, 1, -1, -1},
    {"accessibility-filterkeys-hotkey", 0, 1, -1, -1},
    {"accessibility-togglekeys-hotkey", 0, 1, -1, -1},
    {"accessibility-mousekeys-hotkey", 0, 1, -1, -1},
    {"accessibility-highcontrast-hotkey", 0, 1, -1, -1},
}};
}  // namespace winchisel::core
