#pragma once
#include <array>
namespace winchisel::core {
inline constexpr std::array<PrivacyCatalogEntry, 88> generated_privacy_catalog{{
    {"security-workplace-join-messages", "Workplace Join Message Prompts", "Show Allow my organization to manage my device' prompts throughout Windows", 0},
    {"security-bitlocker-auto-encryption", "BitLocker Auto Encryption", "Controls whether Windows can automatically encrypt drives with BitLocker", 0},
    {"security-wifi-sense", "WiFi-Sense", "Allow sharing WiFi passwords with contacts and connecting to suggested hotspots", 0},
    {"security-automatic-maintenance", "Automatic Maintenance", "Choose if Windows should run automatic system maintenance during idle time", 0},
    {"security-error-reporting", "Windows Error Reporting", "Choose if Windows should collect and send crash reports and error information to Microsoft", 0},
    {"security-remote-assistance", "Remote Assistance", "Choose if other people can connect to your computer remotely to provide technical support", 0},
    {"security-developer-mode", "Developer Mode", "Allows the installation of apps from any source, including loose files", 0},
    {"privacy-content-delivery-allowed", "Content Delivery", "Allows Windows to deliver promotional content and automatically install suggested apps", 1},
    {"privacy-subscribed-content", "Subscribed Content", "Enables promotional content subscriptions from Microsoft and partners throughout Windows", 1},
    {"privacy-feature-management", "Feature Management", "Enables Windows feature management functionality for promotional features and automatic app installations", 1},
    {"privacy-soft-landing", "Soft Landing Experiences", "Enables helpful and promotional soft landing experiences in Windows", 1},
    {"privacy-oem-preinstalled-apps", "OEM Pre-installed Apps", "Prevents OEM manufacturers from automatically installing bloatware apps", 1},
    {"privacy-preinstalled-apps", "Pre-installed Suggested Apps", "Prevents Microsoft from automatically installing suggested apps", 1},
    {"privacy-preinstalled-apps-ever", "Pre-installed Apps History Tracking", "Disables tracking of whether pre-installed apps were ever enabled", 1},
    {"privacy-silent-installed-apps", "Silent App Installation", "Prevents apps from being silently installed in the background", 1},
    {"privacy-lock-screen", "Lock Screen", "Allows users to lock their computer using Windows+L, Start menu, or Ctrl+Alt+Del screen", 2},
    {"privacy-rotating-lock-screen", "Windows Spotlight on Lock Screen", "Displays rotating Windows Spotlight images on your lock screen instead of a static background. Winhance automatically sets the Start Menu Recommended Section to Show when this setting is enabled as it is required", 2},
    {"privacy-lock-screen-overlay", "Lock Screen Fun Facts and Tips", "Displays fun facts, tips, and tricks as an overlay on your lock screen", 2},
    {"privacy-advertising-id", "Let apps show me personalized ads by using my advertising ID", "Windows generates a unique advertising ID that apps use to track your activity and deliver personalized ads based on your behavior across different apps", 3},
    {"privacy-language-list", "Let websites show me locally relevant content by accessing my language list", "Allows websites to access your language preferences so they can automatically display content in your preferred language without requiring manual configuration on each site", 3},
    {"privacy-app-launch-tracking", "Let Windows improve Start and search results by tracking app launches", "Windows records which apps you use most frequently to personalize your Start menu and improve search results, making your most-used apps more accessible", 3},
    {"privacy-settings-content", "Show me suggested content in the Settings app", "Displays promotional content, tips, and feature suggestions within the Windows Settings app. Winhance automatically sets the Start Menu Recommended Section to Show when this setting is enabled as it is required", 3},
    {"privacy-settings-notifications", "Settings App Notifications", "Shows account notifications in the Settings app, including prompts to reauthenticate, backup your device, and manage subscriptions", 3},
    {"privacy-speech-recognition", "Online Speech Recognition", "Use your voice for apps using Microsoft's online speech recognition technology", 4},
    {"privacy-narrator-online-services", "Narrator Online Services", "Allow Narrator to use Microsoft cloud services for features like intelligent image descriptions and enhanced voice models", 4},
    {"privacy-narrator-scripting", "Narrator Scripting Support", "Allow Narrator to execute scripts for automation and custom functionality", 4},
    {"privacy-inking-typing-dictionary", "Custom Inking and Typing Dictionary", "Uses your typing history and handwriting patterns to create a custom dictionary (turning off will clear all words in your custom dictionary)", 5},
    {"privacy-diagnostics", "Send Diagnostic Data", "Send diagnostic data to Microsoft to help improve Windows and keep it secure", 5},
    {"privacy-improve-inking-typing", "Improve inking and typing", "Send optional inking and typing diagnostic data to Microsoft", 6},
    {"privacy-tailored-experiences", "Tailored Experiences", "Let Microsoft use your diagnostic data to show personalized tips, ads and recommendations", 6},
    {"privacy-feedback-frequency", "Allow Windows to ask you for feedback", "Let Windows ask you to provide feedback on experiences in Windows", 6},
    {"privacy-activity-history", "Activity History", "Allows you to jump back into what you were doing with apps, docs, or other activities on startup", 7},
    {"privacy-timeline-suggestions", "Timeline Suggestions", "Shows suggestions in the Windows 10 Timeline feature", 7},
    {"privacy-search-history", "Search history on this device", "Improves search results by allowing Windows Search to store your search history locally on this device (Does not clear existing history)", 8},
    {"privacy-search-highlights", "Show search highlights", "See content suggestions in search", 8},
    {"privacy-search-msa-cloud", "Cloud Content Search for Microsoft account", "Allow Windows Search to show results from apps and services that you are signed in to with your Microsoft account", 8},
    {"privacy-search-aad-cloud", "Cloud Content Search for Work or School account", "Allow Windows Search to show results from apps and services that you are signed in to with your work or school account", 8},
    {"privacy-allow-cortana", "Allow Cortana", "Enables Microsoft's Cortana virtual assistant for voice commands and searches", 8},
    {"privacy-location-services", "Location Services", "Allows Windows and apps to access your device location for location-based features", 9},
    {"privacy-camera-access", "Camera Access", "Allow apps to have camera access", 9},
    {"privacy-microphone-access", "Microphone Access", "Allow apps to have microphone access", 9},
    {"privacy-account-info-access", "Account Info Access", "Allow apps to have account info access", 9},
    {"privacy-app-diagnostic-access", "App Diagnostic Access", "Allow apps to have app diagnostic access", 9},
    {"privacy-onedrive-auto-backup", "OneDrive Automatic Backups", "Controls whether OneDrive automatically backs up your Documents, Pictures, and Desktop folders. Has no effect if OneDrive backups are already active on your device", 9},
    {"privacy-turn-off-copilot", "Windows Copilot", "Controls whether Windows Copilot is available system-wide via group policy for both current user and local machine", 10},
    {"privacy-disable-ai-data-analysis", "AI Data Analysis", "Controls whether Windows AI can analyze user data for personalization and recommendations", 10},
    {"privacy-block-recall-enablement", "Recall Enablement", "Controls whether Windows Recall can be enabled via policy", 10},
    {"privacy-disable-recall-snapshots", "Recall Saving Snapshots", "Allows Windows Recall to save screenshots of your activity for later recall", 10},
    {"privacy-disable-click-to-do", "Click to Do", "Controls whether the Click to Do AI feature is available in Windows", 10},
    {"privacy-disable-settings-agent", "AI Settings Agent", "Controls whether the AI-powered Settings Agent is available in Windows", 10},
    {"privacy-disable-agent-connectors", "AI Agent Connectors", "Controls whether AI agents can use connectors to access external services", 10},
    {"privacy-disable-agent-workspaces", "AI Agent Workspaces", "Controls whether AI Agent Workspaces are available in Windows", 10},
    {"privacy-disable-remote-agent-connectors", "Remote AI Agent Connectors", "Controls whether AI agents can use remote connectors to access remote services", 10},
    {"privacy-disable-copilot-hardware-key", "Copilot Hardware Key", "Controls whether the dedicated Copilot key on keyboards opens Copilot", 10},
    {"privacy-disable-copilot-runtime", "Copilot Runtime", "Controls whether the Copilot runtime is allowed to run via policy", 10},
    {"privacy-copilot-unavailable", "Copilot Availability", "Controls whether Copilot is available in the Windows Shell", 10},
    {"privacy-disable-bing-chat", "Bing Chat Eligibility", "Controls whether the user is eligible for Bing Chat and Copilot in Search", 10},
    {"privacy-deny-generative-ai-access", "Generative AI Access", "Controls whether apps can access the generative AI capability on your device", 10},
    {"privacy-deny-system-ai-models", "System AI Models Access", "Controls whether apps can access system AI models on your device and collect usage data", 10},
    {"privacy-deny-copilot-microphone", "Copilot Microphone Access", "Controls whether Copilot and Office Hub apps have microphone permission", 10},
    {"privacy-disable-paint-ai-image-creator", "Paint AI Image Creator", "Controls whether the AI Image Creator feature is available in Microsoft Paint", 10},
    {"privacy-disable-paint-ai-cocreator", "Paint AI Cocreator", "Controls whether the AI Cocreator feature is available in Microsoft Paint", 10},
    {"privacy-disable-paint-generative-fill", "Paint Generative Fill", "Controls whether the AI Generative Fill feature is available in Microsoft Paint", 10},
    {"privacy-disable-paint-generative-erase", "Paint Generative Erase", "Controls whether the AI Generative Erase feature is available in Microsoft Paint", 10},
    {"privacy-disable-paint-remove-background", "Paint Remove Background", "Controls whether the AI Remove Background feature is available in Microsoft Paint", 10},
    {"privacy-disable-input-insights", "Input Insights", "Controls whether Windows Input Insights can track typing patterns and provide suggestions", 10},
    {"privacy-disable-copilot-nudges", "Copilot Nudges", "Controls whether Copilot promotional nudges and background task notifications are shown", 10},
    {"privacy-disable-consumer-ai-content", "AI Consumer Content", "Controls whether AI-driven consumer account content recommendations are shown", 10},
    {"privacy-edge-copilot-cdp-page-context", "Edge Copilot CDP Page Context", "Controls whether Copilot can use CDP to access page content in Microsoft Edge", 11},
    {"privacy-edge-copilot-page-context", "Edge Copilot Page Context", "Controls whether Copilot can read page content in Microsoft Edge", 11},
    {"privacy-edge-copilot-sidebar", "Edge Copilot Sidebar", "Controls whether the Copilot sidebar is available in Microsoft Edge", 11},
    {"privacy-edge-entra-copilot", "Edge Entra Copilot Page Context", "Controls whether Entra Copilot can access page context in Microsoft Edge", 11},
    {"privacy-edge-m365-copilot-icon", "Edge M365 Copilot Chat Icon", "Controls whether the Microsoft 365 Copilot chat icon is shown in Microsoft Edge", 11},
    {"privacy-edge-ai-history-search", "Edge AI History Search", "Controls whether AI-powered history search is available in Microsoft Edge", 11},
    {"privacy-edge-inline-compose", "Edge Inline AI Compose", "Controls whether AI-powered inline compose suggestions are available in Microsoft Edge", 11},
    {"privacy-edge-local-ai-model", "Edge Local AI Model Settings", "Controls whether local AI model settings are available in Microsoft Edge", 11},
    {"privacy-edge-builtin-ai-apis", "Edge Built-in AI APIs", "Controls whether built-in AI APIs are available in Microsoft Edge for websites to use", 11},
    {"privacy-edge-ai-themes", "Edge AI Generated Themes", "Controls whether AI-generated themes are available in Microsoft Edge", 11},
    {"privacy-edge-devtools-ai", "Edge DevTools AI", "Controls whether AI features are available in Edge DevTools", 11},
    {"privacy-edge-share-history-copilot", "Edge Share History with Copilot", "Controls whether browsing history is shared with Copilot search in Microsoft Edge", 11},
    {"privacy-office-ai-training", "Office AI Training", "Controls whether Office collects AI training data from your usage", 12},
    {"privacy-office-connected-services", "Office Connected Services", "Controls whether Office connected experiences and AI-powered services are available", 12},
    {"privacy-word-copilot", "Word Copilot", "Controls whether Copilot AI features are available in Microsoft Word", 12},
    {"privacy-excel-copilot", "Excel Copilot", "Controls whether Copilot AI features are available in Microsoft Excel", 12},
    {"privacy-onenote-copilot", "OneNote Copilot", "Controls whether Copilot AI features, Copilot notebooks, and Copilot skittle are available in Microsoft OneNote", 12},
    {"privacy-office-content-safety-ai", "Office AI Content Safety", "Controls whether AI content safety features for alt text, rewrite, and summarization are available in Office apps", 12},
    {"privacy-disable-delivery-optimization", "Delivery Optimization P2P Sharing", "Allow Windows to upload downloaded updates to other PCs on the local network and internet. Turn off to save upload bandwidth", 6},
    {"privacy-disable-autologger", "WMI AutoLogger Sessions", "Allow Windows to run background diagnostic logging sessions that consume CPU and disk and feed telemetry. Turn off to reduce background activity", 6},
}};
inline constexpr std::array<PrivacyRegistryRule, 134> generated_privacy_rules{{
    {"security-workplace-join-messages", "SOFTWARE\\Policies\\Microsoft\\Windows\\WorkplaceJoin", "BlockAADWorkplaceJoin", "__MISSING__", "1", 1, 0},
    {"security-bitlocker-auto-encryption", "SYSTEM\\CurrentControlSet\\Control\\BitLocker", "PreventDeviceEncryption", "0", "1", 1, 0},
    {"security-wifi-sense", "Software\\Microsoft\\PolicyManager\\default\\WiFi\\AllowWiFiHotSpotReporting", "Value", "1", "0", 1, 0},
    {"security-wifi-sense", "Software\\Microsoft\\PolicyManager\\default\\WiFi\\AllowAutoConnectToWiFiSenseHotspots", "Value", "1", "0", 1, 0},
    {"security-automatic-maintenance", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\Maintenance", "MaintenanceDisabled", "0", "1", 1, 0},
    {"security-error-reporting", "SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Error Reporting", "Disabled", "0", "1", 1, 0},
    {"security-error-reporting", "SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Error Reporting", "Disabled", "0", "1", 0, 0},
    {"security-remote-assistance", "SYSTEM\\CurrentControlSet\\Control\\Remote Assistance", "fAllowToGetHelp", "1", "0", 1, 0},
    {"security-developer-mode", "Software\\Microsoft\\Windows\\CurrentVersion\\AppModelUnlock", "AllowDevelopmentWithoutDevLicense", "1", "0", 1, 0},
    {"privacy-content-delivery-allowed", "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager", "ContentDeliveryAllowed", "1", "0", 0, 0},
    {"privacy-subscribed-content", "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager", "SubscribedContentEnabled", "__MISSING__", "0", 0, 0},
    {"privacy-feature-management", "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager", "FeatureManagementEnabled", "1", "0", 0, 0},
    {"privacy-soft-landing", "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager", "SoftLandingEnabled", "1", "0", 0, 0},
    {"privacy-oem-preinstalled-apps", "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager", "OemPreInstalledAppsEnabled", "1", "0", 0, 0},
    {"privacy-preinstalled-apps", "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager", "PreInstalledAppsEnabled", "1", "0", 0, 0},
    {"privacy-preinstalled-apps-ever", "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager", "PreInstalledAppsEverEnabled", "__MISSING__", "0", 0, 0},
    {"privacy-silent-installed-apps", "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager", "SilentInstalledAppsEnabled", "1", "0", 0, 0},
    {"privacy-lock-screen", "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon", "DisableLockWorkstation", "0", "1", 1, 0},
    {"privacy-rotating-lock-screen", "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager", "RotatingLockScreenEnabled", "1", "0", 0, 0},
    {"privacy-lock-screen-overlay", "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager", "RotatingLockScreenOverlayEnabled", "1", "0", 0, 0},
    {"privacy-lock-screen-overlay", "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager", "SubscribedContent-338387Enabled", "1", "0", 0, 0},
    {"privacy-advertising-id", "Software\\Microsoft\\Windows\\CurrentVersion\\AdvertisingInfo", "Enabled", "1", "0", 0, 0},
    {"privacy-advertising-id", "Software\\Microsoft\\Windows\\CurrentVersion\\CPSS\\Store\\AdvertisingInfo", "Value", "1", "0", 0, 0},
    {"privacy-advertising-id", "SOFTWARE\\Policies\\Microsoft\\Windows\\AdvertisingInfo", "DisabledByGroupPolicy", "__MISSING__", "1", 0, 0},
    {"privacy-advertising-id", "SOFTWARE\\Policies\\Microsoft\\Windows\\AdvertisingInfo", "DisabledByGroupPolicy", "__MISSING__", "1", 1, 0},
    {"privacy-language-list", "Control Panel\\International\\User Profile", "HttpAcceptLanguageOptOut", "__MISSING__", "1", 0, 0},
    {"privacy-app-launch-tracking", "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced", "Start_TrackProgs", "__MISSING__", "0", 0, 0},
    {"privacy-settings-content", "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager", "SubscribedContent-338393Enabled", "__MISSING__", "0", 0, 0},
    {"privacy-settings-content", "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager", "SubscribedContent-353694Enabled", "__MISSING__", "0", 0, 0},
    {"privacy-settings-content", "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager", "SubscribedContent-353696Enabled", "__MISSING__", "0", 0, 0},
    {"privacy-settings-notifications", "Software\\Microsoft\\Windows\\CurrentVersion\\SystemSettings\\AccountNotifications", "EnableAccountNotifications", "__MISSING__", "0", 0, 0},
    {"privacy-speech-recognition", "Software\\Microsoft\\Speech_OneCore\\Settings\\OnlineSpeechPrivacy", "HasAccepted", "1", "0", 0, 0},
    {"privacy-speech-recognition", "SOFTWARE\\Policies\\Microsoft\\InputPersonalization", "AllowInputPersonalization", "1", "__MISSING__", 0, 0},
    {"privacy-speech-recognition", "SOFTWARE\\Policies\\Microsoft\\InputPersonalization", "AllowInputPersonalization", "1", "__MISSING__", 1, 0},
    {"privacy-narrator-online-services", "Software\\Microsoft\\Narrator\\NoRoam", "OnlineServicesEnabled", "__MISSING__", "0", 0, 0},
    {"privacy-narrator-scripting", "Software\\Microsoft\\Narrator\\NoRoam", "ScriptingEnabled", "__MISSING__", "0", 0, 0},
    {"privacy-inking-typing-dictionary", "Software\\Microsoft\\Windows\\CurrentVersion\\CPSS\\Store\\InkingAndTypingPersonalization", "Value", "1", "0", 0, 0},
    {"privacy-inking-typing-dictionary", "Software\\Microsoft\\Personalization\\Settings", "AcceptedPrivacyPolicy", "1", "0", 0, 0},
    {"privacy-inking-typing-dictionary", "Software\\Microsoft\\InputPersonalization", "RestrictImplicitTextCollection", "0", "1", 0, 0},
    {"privacy-inking-typing-dictionary", "Software\\Microsoft\\InputPersonalization\\TrainedDataStore", "HarvestContacts", "1", "0", 0, 0},
    {"privacy-diagnostics", "Software\\Microsoft\\Windows\\CurrentVersion\\Diagnostics\\DiagTrack", "ShowedToastAtLevel", "3", "1", 0, 0},
    {"privacy-diagnostics", "SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection", "AllowTelemetry", "3", "0", 0, 0},
    {"privacy-diagnostics", "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\DataCollection", "AllowTelemetry", "3", "0", 0, 0},
    {"privacy-diagnostics", "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\DataCollection", "AllowTelemetry", "3", "0", 1, 0},
    {"privacy-diagnostics", "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\DataCollection", "MaxTelemetryAllowed", "3", "0", 0, 0},
    {"privacy-diagnostics", "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\DataCollection", "MaxTelemetryAllowed", "3", "0", 1, 0},
    {"privacy-diagnostics", "SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection", "AllowTelemetry", "3", "0", 1, 0},
    {"privacy-diagnostics", "SOFTWARE\\Policies\\Microsoft\\Windows\\AppCompat", "AITEnable", "__MISSING__", "0", 0, 0},
    {"privacy-diagnostics", "SOFTWARE\\Policies\\Microsoft\\Windows\\AppCompat", "AITEnable", "__MISSING__", "0", 1, 0},
    {"privacy-improve-inking-typing", "Software\\Microsoft\\Input\\TIPC", "Enabled", "1", "0", 0, 0},
    {"privacy-improve-inking-typing", "Software\\Microsoft\\Windows\\CurrentVersion\\CPSS\\Store\\ImproveInkingAndTyping", "Value", "1", "0", 0, 0},
    {"privacy-tailored-experiences", "Software\\Microsoft\\Windows\\CurrentVersion\\Privacy", "TailoredExperiencesWithDiagnosticDataEnabled", "1", "0", 0, 0},
    {"privacy-tailored-experiences", "Software\\Policies\\Microsoft\\Windows\\CloudContent", "DisableTailoredExperiencesWithDiagnosticData", "0", "__MISSING__", 0, 0},
    {"privacy-tailored-experiences", "Software\\Policies\\Microsoft\\Windows\\CloudContent", "DisableTailoredExperiencesWithDiagnosticData", "0", "__MISSING__", 1, 0},
    {"privacy-feedback-frequency", "SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection", "DoNotShowFeedbackNotifications", "__MISSING__", "1", 0, 0},
    {"privacy-feedback-frequency", "SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection", "DoNotShowFeedbackNotifications", "__MISSING__", "1", 1, 0},
    {"privacy-feedback-frequency", "SOFTWARE\\Microsoft\\Siuf\\Rules", "NumberOfSIUFInPeriod", "__MISSING__", "0", 0, 0},
    {"privacy-activity-history", "SOFTWARE\\Policies\\Microsoft\\Windows\\System", "PublishUserActivities", "__MISSING__", "0", 0, 0},
    {"privacy-activity-history", "SOFTWARE\\Policies\\Microsoft\\Windows\\System", "PublishUserActivities", "__MISSING__", "0", 1, 0},
    {"privacy-timeline-suggestions", "Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager", "SubscribedContent-353698Enabled", "__MISSING__", "0", 0, 0},
    {"privacy-search-history", "Software\\Microsoft\\Windows\\CurrentVersion\\SearchSettings", "IsDeviceSearchHistoryEnabled", "__MISSING__", "0", 0, 0},
    {"privacy-search-highlights", "Software\\Microsoft\\Windows\\CurrentVersion\\SearchSettings", "IsDynamicSearchBoxEnabled", "__MISSING__", "0", 0, 0},
    {"privacy-search-msa-cloud", "Software\\Microsoft\\Windows\\CurrentVersion\\SearchSettings", "IsMSACloudSearchEnabled", "__MISSING__", "0", 0, 0},
    {"privacy-search-aad-cloud", "Software\\Microsoft\\Windows\\CurrentVersion\\SearchSettings", "IsAADCloudSearchEnabled", "__MISSING__", "0", 0, 0},
    {"privacy-allow-cortana", "SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search", "AllowCortana", "__MISSING__", "0", 1, 0},
    {"privacy-allow-cortana", "SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search", "AllowCortana", "__MISSING__", "0", 0, 0},
    {"privacy-location-services", "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\location", "Value", "Allow", "Deny", 1, 1},
    {"privacy-location-services", "SOFTWARE\\Policies\\Microsoft\\Windows\\LocationAndSensors", "DisableLocation", "__MISSING__", "__MISSING__", 0, 0},
    {"privacy-location-services", "SOFTWARE\\Policies\\Microsoft\\Windows\\LocationAndSensors", "DisableLocation", "0", "__MISSING__", 1, 0},
    {"privacy-camera-access", "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\webcam", "Value", "Allow", "Deny", 1, 1},
    {"privacy-microphone-access", "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\microphone", "Value", "Allow", "Deny", 1, 1},
    {"privacy-account-info-access", "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\userAccountInformation", "Value", "Allow", "Deny", 1, 1},
    {"privacy-app-diagnostic-access", "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\appDiagnostics", "Value", "Allow", "Deny", 1, 1},
    {"privacy-onedrive-auto-backup", "SOFTWARE\\Policies\\Microsoft\\OneDrive", "KFMBlockOptIn", "__MISSING__", "1", 1, 0},
    {"privacy-onedrive-auto-backup", "SOFTWARE\\Policies\\Microsoft\\OneDrive", "KFMBlockOptIn", "__MISSING__", "1", 0, 0},
    {"privacy-turn-off-copilot", "Software\\Policies\\Microsoft\\Windows\\WindowsCopilot", "TurnOffWindowsCopilot", "0", "1", 0, 0},
    {"privacy-turn-off-copilot", "Software\\Policies\\Microsoft\\Windows\\WindowsCopilot", "TurnOffWindowsCopilot", "__MISSING__", "1", 1, 0},
    {"privacy-disable-ai-data-analysis", "SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsAI", "DisableAIDataAnalysis", "0", "1", 1, 0},
    {"privacy-block-recall-enablement", "SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsAI", "AllowRecallEnablement", "1", "0", 1, 0},
    {"privacy-disable-recall-snapshots", "SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsAI", "TurnOffSavingSnapshots", "0", "1", 1, 0},
    {"privacy-disable-click-to-do", "SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsAI", "DisableClickToDo", "0", "1", 1, 0},
    {"privacy-disable-settings-agent", "SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsAI", "DisableSettingsAgent", "0", "1", 1, 0},
    {"privacy-disable-agent-connectors", "SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsAI", "DisableAgentConnectors", "0", "1", 1, 0},
    {"privacy-disable-agent-workspaces", "SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsAI", "DisableAgentWorkspaces", "0", "1", 1, 0},
    {"privacy-disable-remote-agent-connectors", "SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsAI", "DisableRemoteAgentConnectors", "0", "1", 1, 0},
    {"privacy-disable-copilot-hardware-key", "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CopilotKey", "SetCopilotHardwareKey", "__MISSING__", "", 1, 1},
    {"privacy-disable-copilot-runtime", "SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsAI", "AllowCopilotRuntime", "1", "0", 1, 0},
    {"privacy-copilot-unavailable", "Software\\Microsoft\\Windows\\Shell\\Copilot", "IsCopilotAvailable", "__MISSING__", "0", 0, 0},
    {"privacy-disable-bing-chat", "Software\\Microsoft\\Windows\\Shell\\Copilot\\BingChat", "IsUserEligible", "__MISSING__", "0", 0, 0},
    {"privacy-deny-generative-ai-access", "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\generativeAI", "Value", "Allow", "Deny", 1, 1},
    {"privacy-deny-generative-ai-access", "SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessGenerativeAI", "__MISSING__", "2", 1, 0},
    {"privacy-deny-system-ai-models", "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\systemAIModels", "Value", "Allow", "Deny", 1, 1},
    {"privacy-deny-system-ai-models", "SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy", "LetAppsAccessSystemAIModels", "__MISSING__", "2", 1, 0},
    {"privacy-deny-system-ai-models", "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\systemAIModels", "RecordUsageData", "0", "0", 1, 0},
    {"privacy-deny-copilot-microphone", "Software\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\microphone\\Microsoft.Copilot_8wekyb3d8bbwe", "Value", "Allow", "Deny", 0, 1},
    {"privacy-deny-copilot-microphone", "Software\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\microphone\\Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe", "Value", "__MISSING__", "Deny", 0, 1},
    {"privacy-disable-paint-ai-image-creator", "SOFTWARE\\Policies\\Microsoft\\Paint", "DisableImageCreator", "0", "1", 1, 0},
    {"privacy-disable-paint-ai-cocreator", "SOFTWARE\\Policies\\Microsoft\\Paint", "DisableCocreator", "0", "1", 1, 0},
    {"privacy-disable-paint-generative-fill", "SOFTWARE\\Policies\\Microsoft\\Paint", "DisableGenerativeFill", "0", "1", 1, 0},
    {"privacy-disable-paint-generative-erase", "SOFTWARE\\Policies\\Microsoft\\Paint", "DisableGenerativeErase", "0", "1", 1, 0},
    {"privacy-disable-paint-remove-background", "SOFTWARE\\Policies\\Microsoft\\Paint", "DisableRemoveBackground", "0", "1", 1, 0},
    {"privacy-disable-input-insights", "Software\\Microsoft\\input\\Settings", "InsightsEnabled", "1", "0", 0, 0},
    {"privacy-disable-copilot-nudges", "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced", "ShowCopilotNudges", "__MISSING__", "0", 0, 0},
    {"privacy-disable-consumer-ai-content", "SOFTWARE\\Policies\\Microsoft\\Windows\\CloudContent", "DisableConsumerAccountStateContent", "0", "1", 1, 0},
    {"privacy-edge-copilot-cdp-page-context", "SOFTWARE\\Policies\\Microsoft\\Edge", "CopilotCDPPageContext", "1", "0", 1, 0},
    {"privacy-edge-copilot-page-context", "SOFTWARE\\Policies\\Microsoft\\Edge", "CopilotPageContext", "1", "0", 1, 0},
    {"privacy-edge-copilot-sidebar", "SOFTWARE\\Policies\\Microsoft\\Edge", "HubsSidebarEnabled", "1", "0", 1, 0},
    {"privacy-edge-entra-copilot", "SOFTWARE\\Policies\\Microsoft\\Edge", "EdgeEntraCopilotPageContext", "1", "0", 1, 0},
    {"privacy-edge-m365-copilot-icon", "SOFTWARE\\Policies\\Microsoft\\Edge", "Microsoft365CopilotChatIconEnabled", "1", "0", 1, 0},
    {"privacy-edge-ai-history-search", "SOFTWARE\\Policies\\Microsoft\\Edge", "EdgeHistoryAISearchEnabled", "1", "0", 1, 0},
    {"privacy-edge-inline-compose", "SOFTWARE\\Policies\\Microsoft\\Edge", "ComposeInlineEnabled", "1", "0", 1, 0},
    {"privacy-edge-local-ai-model", "SOFTWARE\\Policies\\Microsoft\\Edge", "GenAILocalFoundationalModelSettings", "0", "1", 1, 0},
    {"privacy-edge-builtin-ai-apis", "SOFTWARE\\Policies\\Microsoft\\Edge", "BuiltInAIAPIsEnabled", "1", "0", 1, 0},
    {"privacy-edge-ai-themes", "SOFTWARE\\Policies\\Microsoft\\Edge", "AIGenThemesEnabled", "1", "0", 1, 0},
    {"privacy-edge-devtools-ai", "SOFTWARE\\Policies\\Microsoft\\Edge", "DevToolsGenAiSettings", "0", "2", 1, 0},
    {"privacy-edge-share-history-copilot", "SOFTWARE\\Policies\\Microsoft\\Edge", "ShareBrowsingHistoryWithCopilotSearchAllowed", "1", "0", 1, 0},
    {"privacy-office-ai-training", "Software\\Policies\\Microsoft\\office\\16.0\\common\\ai\\training", "optionalconnectedexperiencesenabled", "1", "0", 0, 0},
    {"privacy-office-connected-services", "Software\\Policies\\Microsoft\\office\\16.0\\common\\privacy", "controllerconnectedservicesenabled", "0", "2", 0, 0},
    {"privacy-office-connected-services", "Software\\Policies\\Microsoft\\office\\16.0\\common\\privacy", "usercontentdisabled", "__MISSING__", "2", 0, 0},
    {"privacy-word-copilot", "Software\\Microsoft\\Office\\16.0\\Word\\Options", "EnableCopilot", "__MISSING__", "0", 0, 0},
    {"privacy-excel-copilot", "Software\\Microsoft\\Office\\16.0\\Excel\\Options", "EnableCopilot", "__MISSING__", "0", 0, 0},
    {"privacy-onenote-copilot", "Software\\Microsoft\\Office\\16.0\\OneNote\\Options\\Other", "EnableCopilot", "__MISSING__", "0", 0, 0},
    {"privacy-onenote-copilot", "Software\\Microsoft\\Office\\16.0\\OneNote\\Options\\Other", "EnableCopilotNotebooks", "__MISSING__", "0", 0, 0},
    {"privacy-onenote-copilot", "Software\\Microsoft\\Office\\16.0\\OneNote\\Options\\Other", "EnableCopilotSkittle", "__MISSING__", "0", 0, 0},
    {"privacy-office-content-safety-ai", "Software\\Policies\\Microsoft\\office\\16.0\\common\\ai", "contentsafetyserviceenabled", "1", "0", 0, 0},
    {"privacy-disable-delivery-optimization", "SOFTWARE\\Policies\\Microsoft\\Windows\\DeliveryOptimization", "DODownloadMode", "1", "0", 1, 0},
    {"privacy-disable-autologger", "SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\AppModel", "Start", "1", "0", 1, 0},
    {"privacy-disable-autologger", "SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\CloudExperienceHostOobe", "Start", "1", "0", 1, 0},
    {"privacy-disable-autologger", "SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\DataMarket", "Start", "1", "0", 1, 0},
    {"privacy-disable-autologger", "SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\DiagLog", "Start", "1", "0", 1, 0},
    {"privacy-disable-autologger", "SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\Diagtrack-Listener", "Start", "1", "0", 1, 0},
    {"privacy-disable-autologger", "SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\LwtNetLog", "Start", "1", "0", 1, 0},
    {"privacy-disable-autologger", "SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\SQMLogger", "Start", "1", "0", 1, 0},
    {"privacy-disable-autologger", "SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\WdiContextLog", "Start", "1", "0", 1, 0},
}};
}
