#include "winchisel/platform/performance.hpp"
#include <Windows.h>
#include <taskschd.h>
#include <comdef.h>
#include <array>
#include <algorithm>
#include <string>
#include <unordered_map>
#include <mutex>
#pragma comment(lib, "taskschd.lib")
#pragma comment(lib, "ole32.lib")
namespace winchisel::platform { namespace {
std::string_view task_path(std::string_view id){static constexpr std::pair<std::string_view,std::string_view> tasks[]{
{"CompatibilityAppraiserTask","\\Microsoft\\Windows\\Application Experience\\Microsoft Compatibility Appraiser"},{"ProgramDataUpdaterTask","\\Microsoft\\Windows\\Application Experience\\ProgramDataUpdater"},{"CEIPConsolidatorTask","\\Microsoft\\Windows\\Customer Experience Improvement Program\\Consolidator"},{"UsbCeipTask","\\Microsoft\\Windows\\Customer Experience Improvement Program\\UsbCeip"},{"DiskDiagnosticTask","\\Microsoft\\Windows\\DiskDiagnostic\\Microsoft-Windows-DiskDiagnosticDataCollector"},{"FeedbackDmClientTask","\\Microsoft\\Windows\\Feedback\\Siuf\\DmClient"},{"FeedbackDmClientDownloadTask","\\Microsoft\\Windows\\Feedback\\Siuf\\DmClientOnScenarioDownload"},{"ErrorReportingQueueTask","\\Microsoft\\Windows\\Windows Error Reporting\\QueueReporting"},{"SqmTask","\\Microsoft\\Windows\\PI\\Sqm-Tasks"},{"MareBackupTask","\\Microsoft\\Windows\\Application Experience\\MareBackup"},{"StartupAppTask","\\Microsoft\\Windows\\Application Experience\\StartupAppTask"},{"MapsUpdateTask","\\Microsoft\\Windows\\Maps\\MapsUpdateTask"},{"AutochkProxyTask","\\Microsoft\\Windows\\Autochk\\Proxy"},{"FamilySafetyTask","\\Microsoft\\Windows\\Shell\\FamilySafetyMonitor"},{"PowerEfficiencyTask","\\Microsoft\\Windows\\Power Efficiency Diagnostics\\AnalyzeSystem"},{"WindowsAIRecallConfig","\\Microsoft\\Windows\\WindowsAI\\RecallConfiguration"},{"WindowsAIRecallPipeline","\\Microsoft\\Windows\\WindowsAI\\RecallPipeline"},{"OfficeActionsServer","\\Microsoft\\Office\\Office Actions Server"}};for(auto const&[key,path]:tasks)if(key==id)return path;return{};}
std::pair<DWORD,std::string> run(std::wstring command){SECURITY_ATTRIBUTES sa{sizeof(sa),nullptr,TRUE};HANDLE read{},write{};if(!CreatePipe(&read,&write,&sa,0))return{GetLastError(),{}};SetHandleInformation(read,HANDLE_FLAG_INHERIT,0);STARTUPINFOW si{};si.cb=sizeof(si);si.dwFlags=STARTF_USESTDHANDLES|STARTF_USESHOWWINDOW;si.wShowWindow=SW_HIDE;si.hStdOutput=write;si.hStdError=write;PROCESS_INFORMATION pi{};if(!CreateProcessW(nullptr,command.data(),nullptr,nullptr,TRUE,CREATE_NO_WINDOW,nullptr,nullptr,&si,&pi)){auto e=GetLastError();CloseHandle(read);CloseHandle(write);return{e,{}};}CloseHandle(write);std::string out;std::array<char,512>b{};DWORD n{};while(ReadFile(read,b.data(),static_cast<DWORD>(b.size()),&n,nullptr)&&n)out.append(b.data(),n);WaitForSingleObject(pi.hProcess,INFINITE);DWORD code{};GetExitCodeProcess(pi.hProcess,&code);CloseHandle(read);CloseHandle(pi.hThread);CloseHandle(pi.hProcess);return{code,std::move(out)};}
winchisel::core::Error error(std::string detail){return{winchisel::core::ErrorCode::platform,"performance_command_failed",std::move(detail)};}
}
winchisel::core::Result<int> read_dns_profile(){auto[code,out]=run(L"netsh.exe interface ipv4 show dnsservers");if(code)return std::unexpected(error(std::to_string(code)));out.erase(std::remove_if(out.begin(),out.end(),[](char c){return c=='\r'||c=='\n'||c==' ';}),out.end());constexpr std::array values{"","1.1.1.11.0.0.1","1.1.1.21.0.0.2","1.1.1.31.0.0.3","8.8.8.88.8.4.4","9.9.9.9149.112.112.112","208.67.222.222208.67.220.220"};for(std::size_t i=1;i<values.size();++i)if(out.find(values[i])!=std::string::npos)return static_cast<int>(i);return 0;}
winchisel::core::Result<void> write_dns_profile(int index){constexpr std::array servers{L"",L"1.1.1.1",L"1.1.1.2",L"1.1.1.3",L"8.8.8.8",L"9.9.9.9",L"208.67.222.222"};auto[code,out]=run(L"netsh.exe interface ipv4 set dnsservers name=all source="+std::wstring(index>0&&index<static_cast<int>(servers.size())?L"static address="+std::wstring(servers[index]):L"dhcp"));if(code)return std::unexpected(error(std::to_string(code)));return{};}

winchisel::core::Result<ITaskService*> open_task_service(){
    HRESULT hr=CoInitializeEx(nullptr,COINIT_MULTITHREADED); if(FAILED(hr)&&hr!=RPC_E_CHANGED_MODE)return std::unexpected(error(std::to_string(hr)));
    ITaskService* service{}; hr=CoCreateInstance(CLSID_TaskScheduler,nullptr,CLSCTX_INPROC_SERVER,IID_PPV_ARGS(&service)); if(FAILED(hr))return std::unexpected(error(std::to_string(hr)));
    VARIANT empty; VariantInit(&empty); hr=service->Connect(empty,empty,empty,empty); if(FAILED(hr)){service->Release();return std::unexpected(error(std::to_string(hr)));} return service;
}
winchisel::core::Result<IRegisteredTask*> open_task(std::string_view full){auto service=open_task_service();if(!service)return std::unexpected(service.error());BSTR root_path=SysAllocString(L"\\");ITaskFolder* root{};auto hr=(*service)->GetFolder(root_path,&root);SysFreeString(root_path);if(FAILED(hr)){(*service)->Release();return std::unexpected(error(std::to_string(hr)));}std::wstring path(full.begin(),full.end());BSTR value=SysAllocString(path.c_str());IRegisteredTask* task{};hr=root->GetTask(value,&task);SysFreeString(value);root->Release();(*service)->Release();if(FAILED(hr))return std::unexpected(error(std::to_string(hr)));return task;}
winchisel::core::Result<bool> read_scheduled_task(std::string_view id){auto full=task_path(id);if(full.empty())return std::unexpected(error("unknown scheduled task"));auto task=open_task(full);if(!task)return false;VARIANT_BOOL enabled{};auto hr=(*task)->get_Enabled(&enabled);(*task)->Release();if(FAILED(hr))return std::unexpected(error(std::to_string(hr)));return enabled==VARIANT_TRUE;}
winchisel::core::Result<void> write_scheduled_task(std::string_view id,bool enabled){auto full=task_path(id);if(full.empty())return std::unexpected(error("unknown scheduled task"));auto task=open_task(full);if(!task)return std::unexpected(task.error());auto hr=(*task)->put_Enabled(enabled?VARIANT_TRUE:VARIANT_FALSE);(*task)->Release();if(FAILED(hr))return std::unexpected(error(std::to_string(hr)));return{};}
}
