#include "winchisel/platform/performance.hpp"
#include <Windows.h>
#include <array>
#include <algorithm>
#include <string>
#include <unordered_map>
#include <mutex>
namespace winchisel::platform { namespace {
std::mutex task_cache_mutex;
std::unordered_map<std::string,bool> task_cache;
bool task_cache_ready{};
std::string_view task_path(std::string_view id){static constexpr std::pair<std::string_view,std::string_view> tasks[]{
{"CompatibilityAppraiserTask","\\Microsoft\\Windows\\Application Experience\\Microsoft Compatibility Appraiser"},{"ProgramDataUpdaterTask","\\Microsoft\\Windows\\Application Experience\\ProgramDataUpdater"},{"CEIPConsolidatorTask","\\Microsoft\\Windows\\Customer Experience Improvement Program\\Consolidator"},{"UsbCeipTask","\\Microsoft\\Windows\\Customer Experience Improvement Program\\UsbCeip"},{"DiskDiagnosticTask","\\Microsoft\\Windows\\DiskDiagnostic\\Microsoft-Windows-DiskDiagnosticDataCollector"},{"FeedbackDmClientTask","\\Microsoft\\Windows\\Feedback\\Siuf\\DmClient"},{"FeedbackDmClientDownloadTask","\\Microsoft\\Windows\\Feedback\\Siuf\\DmClientOnScenarioDownload"},{"ErrorReportingQueueTask","\\Microsoft\\Windows\\Windows Error Reporting\\QueueReporting"},{"SqmTask","\\Microsoft\\Windows\\PI\\Sqm-Tasks"},{"MareBackupTask","\\Microsoft\\Windows\\Application Experience\\MareBackup"},{"StartupAppTask","\\Microsoft\\Windows\\Application Experience\\StartupAppTask"},{"MapsUpdateTask","\\Microsoft\\Windows\\Maps\\MapsUpdateTask"},{"AutochkProxyTask","\\Microsoft\\Windows\\Autochk\\Proxy"},{"FamilySafetyTask","\\Microsoft\\Windows\\Shell\\FamilySafetyMonitor"},{"PowerEfficiencyTask","\\Microsoft\\Windows\\Power Efficiency Diagnostics\\AnalyzeSystem"},{"WindowsAIRecallConfig","\\Microsoft\\Windows\\WindowsAI\\RecallConfiguration"},{"WindowsAIRecallPipeline","\\Microsoft\\Windows\\WindowsAI\\RecallPipeline"},{"OfficeActionsServer","\\Microsoft\\Office\\Office Actions Server"}};for(auto const&[key,path]:tasks)if(key==id)return path;return{};}
std::pair<DWORD,std::string> run(std::string command){SECURITY_ATTRIBUTES sa{sizeof(sa),nullptr,TRUE};HANDLE read{},write{};if(!CreatePipe(&read,&write,&sa,0))return{GetLastError(),{}};SetHandleInformation(read,HANDLE_FLAG_INHERIT,0);STARTUPINFOA si{};si.cb=sizeof(si);si.dwFlags=STARTF_USESTDHANDLES|STARTF_USESHOWWINDOW;si.wShowWindow=SW_HIDE;si.hStdOutput=write;si.hStdError=write;PROCESS_INFORMATION pi{};if(!CreateProcessA(nullptr,command.data(),nullptr,nullptr,TRUE,CREATE_NO_WINDOW,nullptr,nullptr,&si,&pi)){auto e=GetLastError();CloseHandle(read);CloseHandle(write);return{e,{}};}CloseHandle(write);std::string out;std::array<char,512>b{};DWORD n{};while(ReadFile(read,b.data(),static_cast<DWORD>(b.size()),&n,nullptr)&&n)out.append(b.data(),n);WaitForSingleObject(pi.hProcess,INFINITE);DWORD code{};GetExitCodeProcess(pi.hProcess,&code);CloseHandle(read);CloseHandle(pi.hThread);CloseHandle(pi.hProcess);return{code,std::move(out)};}
winchisel::core::Error error(std::string detail){return{winchisel::core::ErrorCode::platform,"performance_command_failed",std::move(detail)};}
}
winchisel::core::Result<int> read_dns_profile(){auto[code,out]=run("powershell.exe -NoProfile -NonInteractive -Command \"(Get-DnsClientServerAddress -AddressFamily IPv4|?{$_.ServerAddresses.Count -gt 0}|select -First 1 -Expand ServerAddresses)-join ','\"");if(code)return std::unexpected(error(std::to_string(code)));out.erase(std::remove_if(out.begin(),out.end(),[](char c){return c=='\r'||c=='\n'||c==' ';}),out.end());constexpr std::array values{"","1.1.1.1,1.0.0.1","1.1.1.2,1.0.0.2","1.1.1.3,1.0.0.3","8.8.8.8,8.8.4.4","9.9.9.9,149.112.112.112","208.67.222.222,208.67.220.220"};for(std::size_t i=1;i<values.size();++i)if(out==values[i])return static_cast<int>(i);return 0;}
winchisel::core::Result<void> write_dns_profile(int index){constexpr std::array servers{"","1.1.1.1','1.0.0.1","1.1.1.2','1.0.0.2","1.1.1.3','1.0.0.3","8.8.8.8','8.8.4.4","9.9.9.9','149.112.112.112","208.67.222.222','208.67.220.220"};std::string action=index>0&&index<static_cast<int>(servers.size())?"-ServerAddresses @('"+std::string(servers[index])+"')":"-ResetServerAddresses";auto[code,out]=run("powershell.exe -NoProfile -NonInteractive -Command \"Get-NetAdapter|%{Set-DnsClientServerAddress -InterfaceIndex $_.InterfaceIndex "+action+"}\"");if(code)return std::unexpected(error(std::to_string(code)));return{};}
winchisel::core::Result<bool> read_scheduled_task(std::string_view id){auto full=task_path(id);if(full.empty())return std::unexpected(error("unknown scheduled task"));std::scoped_lock lock(task_cache_mutex);if(!task_cache_ready){auto[code,out]=run("powershell.exe -NoProfile -NonInteractive -Command \"Get-ScheduledTask -ErrorAction SilentlyContinue|%{$f=('\\'+$_.TaskPath.Trim('\\')+'\\'+$_.TaskName).Replace('\\\\','\\');$f+'='+[int]$_.Settings.Enabled}\"");if(code)return std::unexpected(error(std::to_string(code)));std::size_t start{};while(start<out.size()){auto end=out.find_first_of("\r\n",start);if(end==std::string::npos)end=out.size();auto line=out.substr(start,end-start);auto separator=line.rfind('=');if(separator!=std::string::npos)task_cache[line.substr(0,separator)]=line.substr(separator+1)=="1";start=out.find_first_not_of("\r\n",end);if(start==std::string::npos)break;}task_cache_ready=true;}auto found=task_cache.find(std::string(full));return found!=task_cache.end()?found->second:false;}
winchisel::core::Result<void> write_scheduled_task(std::string_view id,bool enabled){auto full=task_path(id);if(full.empty())return std::unexpected(error("unknown scheduled task"));auto split=full.find_last_of('\\');auto path=full.substr(0,split+1),name=full.substr(split+1);auto verb=enabled?"Enable-ScheduledTask":"Disable-ScheduledTask";auto[code,out]=run("powershell.exe -NoProfile -NonInteractive -Command \""+std::string(verb)+" -TaskPath '"+std::string(path)+"' -TaskName '"+std::string(name)+"' -ErrorAction Stop\"");if(code)return std::unexpected(error(std::to_string(code)));{std::scoped_lock lock(task_cache_mutex);task_cache[std::string(full)]=enabled;}return{};}
}
